### ISSUE TITLE
Some file names (e.g. net/config-*-linux) are incompatible with git on windows

### ISSUE THREAD

**Issue by arod-1** [webmin/webmin#1]
Git on windows (msysGit) fails to create files with \* in their names.
this may be a git issue. however, it's possible that it would be good to solve this problem in webmin (i.e. put them in a different name in the repo, and have the install procedure rename them, or maybe use different name altogether)

**Comment by swelljoe** [comment]
This has been fixed by changing all \* filenames to use AL, instead, a couple of versions back. I've confirmed it can be cloned on Windows, but haven't done much else with the source, as I don't usually work on Windows. Feel free to open a new issue if there are any other problems with checkouts on Windows.

I know this is a really old issue, but I see that Perl has a *great* Windows experience these days, so there's no reason Webmin shouldn't be nice to develop on Windows too (well, except for all the other weird things about Windows that make it hard...but, we'll cross those bridges when we come to them).
