### ISSUE TITLE
High CPU usage - [/usr/share/webm] <defunct>

### ISSUE THREAD

**Issue by webgear1** [webmin/webmin#1083]
Hello,

Since a few hours I have all my sites that are timed out. I looked at the CPU on webmin, there is a process that uses all the CPU : [/usr/share/webm] <defunct>

[screenshot](https://user-images.githubusercontent.com/53439969/62060476-79e38a00-b225-11e9-82c8-4c58562073d4.jpg)

I don't know what it is, I have no idea how to fix it.
Can you help me?

Thank you :)

**Comment by rostovtsev** [comment]
Hi,

What is the output of `top` command in console? Does it have Webmin processes to top in consuming CPU resources or it only happens when run in UI?

If you go to console and try to shutdown Webmin by running `service webmin stop` does it change anything?

**Comment by webgear1** [comment]
My server looks like back. I don't know what happened. Here is the top command (if it helps).
![screenshot](https://user-images.githubusercontent.com/53439969/62063037-6f77bf00-b22a-11e9-9068-9280234544e3.jpg)

**Comment by rostovtsev** [comment]
:) No, what is `top` command output if run in console (logged in via SSH).

**Comment by webgear1** [comment]
> :) No, what is `top` command output if run in console (logged in via SSH).

Sorry wrong screen :
![putty_2AOT9Xwguw](https://user-images.githubusercontent.com/53439969/62063598-70f5b700-b22b-11e9-9d69-3f594de2c66c.jpg)

**Comment by rostovtsev** [comment]
Okay, as you can see Webmin doesn't use any resources, as expected. It just happens on the time the script, proc module, is querying the data, and results are going to the final output. You can prevent this from happening by using module's configuration.

Speaking about `php-fpm` processes. In Webmin you can click on the process id to see what is happening. Check Apache and PHP logs for more details as well. Usually high CPU usage caused by multimedia libs for processing videos or photos but not limited to it. You need to know your webapp and want it's doing (or could be doing) to tackle the problem.

**Comment by webgear1** [comment]
Okay, I'll look into PHP. Thank you very much for your help !
