### ISSUE TITLE
File Manager - Unable to delete

### ISSUE THREAD

**Issue by dhornford** [webmin/webmin#1098]
After upgrading to 1.930 I am unable to delete files in the file manager module.
I get the following error (including the typo)
   Following errors occured while performing operation
	* 
  [filename] - unable to delete: No such file or directory

The same files can be renamed & deleted from the command line.

**Comment by jcameron** [comment]
What was the full path / filename of the file you were trying to delete?

**Comment by dhornford** [comment]
Multiple files

Most were Tomcat logs that are tied to an alfresco install. I’m too lazy to dig through what the installer did. These are in /opt

 

The one was: /etc/httpd/conf.d/ssl.conf.bak

My Alfresco installer used /alf-ssl.conf, which means every update of http I have to clean-up. But its built the way he likes.

**Comment by rostovtsev** [comment]
This issue happens only in older themes. It's been fixed recently. As a work around you can try Authentic Theme or apply the [patch](https://github.com/webmin/webmin/commit/1f5600967f2d7873a443122db2298a06d1d7fd0b).

**Comment by dhornford** [comment]
Ilia, Thanks I switched to Authentic from Grey Framed and the error went away.

 

Regards Dave

**Comment by joergma** [comment]
Thanks. I applied the patch and it works flawlessly with Gray Framed theme.
Will this patch also work with Authentic theme?

Regards, Jörg

**Comment by rostovtsev** [comment]
Latest changes to Webmin and Authentic Theme solves all of those issues, including older themes.

It will also work with directories/files containing encoded chars, like `%2F` and etc.

**Comment by Vitusware** [comment]
Hi, this might be an old thread but for some reasons I still have this issue, just updated to **Authentic theme version** | 21.09.4 and it is still the same.  

>  [foldername]: unable to delete - no such file or directory

Should I remove the whole theme and re-install it to get this to work properly? 

**System:**   CentOS Linux 7.9.2009  **Webmin version** 2.101 	**Usermin version** 2.001 **Virtualmin version** 7.8.2  

**Kernel and CPU**	Linux 3.10.0-1160.102.1.el7.x86_64 on x86_64

Thank you

**Comment by iliajie** [comment]
I'm not sure what the real issue is? I think you don't need to delete anything, start from trying in another browser's incognito tab.

**Comment by Vitusware** [comment]
> I'm not sure what the real issue is? I think you don't need to delete it, start from trying in another browser's incognito tab.

Hi,  Thanks for the speedy reply.

Well I've tried anything, fact is that using the _framed theme_  it does work without any issues.
Like in the several message I've found, so this does look like a theme issue here.. 
I've tired the browser's incognito tab, without the same result.
Files and folders can be created, renamed and selected.
Files can be delete, even in bulk with several selected.

folders or directories however can not be deleted, resulting in the error:
![image](https://github.com/webmin/webmin/assets/29035591/2fdeb55a-996d-4f52-ac0e-5b6df75fa1ca)

As said before this is not an issue whatsoever in the _framed theme_

I have this issue for as long I can remember not sure when it started though..
but do know it suddenly occurred and have it ever since.

I encountered it again last night so I started looking and found this thread about it stating it was resolved.. 
Which made me even more curious because apparently  I still have this issue 😅

so any help is much appreciated.

Thank you.

**Comment by iliajie** [comment]
I can also reproduce this "problem" if I create directory `A` under `/tmp` in File Manager, and then delete it using `rm -rf /tmp/A` via command line, and then as I try to delete it in File Manager I get this error.

This is expected.

**Comment by Vitusware** [comment]
> I can also reproduce this "problem" if I create directory `A` under `/tmp` in File Manager, and then delete it using `rm -rf /tmp/A` via command line, and then as I try to delete it in File Manager I get this error.
> 
> This is expected.

Hi, thanks for the reply.

Now you are confusing me; 
When you already have deleted the directory, there is no need to delete is again in filemanager, now is there?

It's obvious you get the error when you try to dele a directory that is not there..
And  if you have refereshed filemanager _A_ would not be there listed because it is already removed.
So you should not be able to delete this directory twice by mistake.

But,  if you create a directory within filemanager and try to delete that from filemanager, do you get the error?
Because when I do I get that error..

Thank you.

**Comment by iliajie** [comment]
> And if you have refreshed File Manager, `A` would not be there listed because it is already removed.

Yes, correct.

> But, if you create a directory within filemanager and try to delete that from filemanager, do you get the error?

Of course not!

> Because when I do I get that error..

You need to tell everything about your environment and setup, and provide steps to reproduce the issue.

**Comment by Vitusware** [comment]
This is my setup:
**System:**   CentOS Linux 7.9.2009  **Webmin version** 2.101 	**Usermin version** 2.001 **Virtualmin version** 7.8.2  

**Kernel and CPU**	Linux 3.10.0-1160.102.1.el7.x86_64 on x86_64

* log in, go to Webmin,  start filemanager (yes first domain will do just nicely, any other domain will give the same error)
Create a directory,  select it and try and remove it..
There is the error..

Those are the steps in short, you can also create files in this directory and remove them before you remove the directory, rename the directory proir to removal.. every thing works except the directroy removal..

I hope this clears any confusion there is..

Mind you:  switching to _Framed There_  fixes everything directory removal works using that Theme..
Hence my conclusion  this is a Theme bases issue..

Thank you

**Comment by iliajie** [comment]
I'm pretty confident that it isn't something happening on my clean CentOS Virtualmin install!

Do you think I could just login remotely to your system, with the same user you're having a problem with, and have a real-time look? I cannot reproduce this problem that you're having!

**Comment by iliajie** [comment]
Also, which browser are you using? Can you perhaps instead of providing remote login make step by step screenshots, so I understand what you're doing exactly?

**Comment by Vitusware** [comment]
> I'm pretty confident that it isn't something happening on my clean CentOS Virtualmin install!
> 
> Do you think I could just login remotely to your system, with the same user you're having a problem with, and have a real-time look? I cannot reproduce this problem that you're having!

Well, I'm full adming so that would be a bit of a risk I would take, no offence intended of course..

But I might make a test server with a new account ans have a look if this issue occourse there as wel.

If so I could give the the credentials of this server and see for yourself without me risking my whole system ;)

Just a sec to set it up, please wait whi;le I go and check this.

and thank you for your help in this I do apreciate your help.

**Comment by Vitusware** [comment]
> Also, which browser are you using? Can you perhaps instead of providing remote login make step by step screenshots, so I understand what you're doing exactly?

I'm using chrome, from several machines, ie. computers and laptops, with the same result..
Tried to use different browsers like safari on my ipad, but that wasn't a success (could not connect :D

**Comment by Vitusware** [comment]
Right..

Now this is confusing 😅

I've created a new server, and loggin in as this server user..
Doing exactly the same.. and now it works.. Wait .. 🤔

So that could mean the issue is in my main system account ..  so i have to check that out..

Not sure what I going to do next abolut that one, but I got something to dive into..

Thanks anyway for your idea making anouther account, to test that..

Going to get back on this for you..

**Comment by iliajie** [comment]
On your main system - are you logged in as root user or sudo-capable user?

**Comment by Vitusware** [comment]
> On your main system - are you logged in as root user or sudo-capable user?

it's a sudo capable user , root is disabled for security purposes, however it is member of the root group.
This is a simple  security trick used many times on different servers without any problems, until this weird issue.

Still not sure that could be an issue with the  theme though..

**Comment by iliajie** [comment]
> it's a sudo capable user

What is the content of the following files on your system:


```
/etc/webmin/filemin/root.acl
/etc/webmin/miniserv.conf
```

**Comment by Vitusware** [comment]
> > it's a sudo capable user
> 
> What is the content of the following files on your system:
> 
> ```
> /etc/webmin/filemin/root.acl

There is no root.acl file in that directory

> /etc/webmin/miniserv.conf

`port=10000
addtype_cgi=internal/cgi
realm=Webmin Server
logfile=/var/webmin/miniserv.log
errorlog=/var/webmin/miniserv.error
pidfile=/var/webmin/miniserv.pid
logtime=168
ssl=1
no_ssl2=1
no_ssl3=1
no_tls1=1
no_tls1_1=1
ssl_honorcipherorder=1
no_sslcompression=1
env_WEBMIN_CONFIG=/etc/webmin
env_WEBMIN_VAR=/var/webmin
atboot=1
logout=/etc/webmin/logout-flag
listen=10000
denyfile=\.pl$
log=1
blockhost_failures=5
blockhost_time=60
syslog=1
ipv6=1
session=1
userfile=/etc/webmin/miniserv.users
keyfile=/etc/webmin/linux.vitusware.com.key
passwd_file=/etc/shadow
passwd_uindex=0
passwd_pindex=1
passwd_cindex=2
passwd_mindex=4
passwd_mode=0
preroot=authentic-theme
passdelay=1
login_script=/etc/webmin/login.pl
logout_script=/etc/webmin/logout.pl
cipher_list_def=1
failed_script=/etc/webmin/failed.pl
sessiononly=/virtual-server/remote.cgi
preload=virtual-server=virtual-server/virtual-server-lib-funcs.pl virtual-server=virtual-server/feature-unix.pl virtual-server=virtual-server/feature-dir.pl virtual-server=virtual-server/feature-dns.pl virtual-server=virtual-server/feature-mail.pl virtual-server=virtual-server/feature-web.pl virtual-server=virtual-server/feature-webalizer.pl virtual-server=virtual-server/feature-ssl.pl virtual-server=virtual-server/feature-logrotate.pl virtual-server=virtual-server/feature-mysql.pl virtual-server=virtual-server/feature-postgres.pl virtual-server=virtual-server/feature-ftp.pl virtual-server=virtual-server/feature-spam.pl virtual-server=virtual-server/feature-virus.pl virtual-server=virtual-server/feature-webmin.pl virtual-server=virtual-server/feature-virt.pl virtual-server=virtual-server/feature-virt6.pl
ssl_cipher_list=ECDHE-RSA-AES256-SHA384:AES256-SHA256:AES256-SHA256:RC4:HIGH:MEDIUM:+TLSv1:+TLSv1.1:+TLSv1.2:!MD5:!ADH:!aNULL:!eNULL:!NULL:!DH:!ADH:!EDH:!AESGCM
error_handler_403=403.cgi
error_handler_404=404.cgi
error_handler_401=401.cgi
nolog=\/stats\.cgi\?xhr\-stats\=general
premodules=WebminCore
ipcert_linux.vitusware.com,*.linux.vitusware.com=/home/linux.vitusware.com/ssl.cert
ipkey_linux.vitusware.com,*.linux.vitusware.com=/home/linux.vitusware.com/ssl.key
logouttimes=
ipextracas_linux.vitusware.com,*.linux.vitusware.com=/home/linux.vitusware.com/ssl.ca
extracas=/etc/webmin/linux.vitusware.com.ca
certfile=/etc/webmin/linux.vitusware.com.cert
root=/usr/libexec/webmin
mimetypes=/usr/libexec/webmin/mime.types
server=MiniServ/2.101
`

That's all I have at this time ;)

**Comment by Vitusware** [comment]
Just thought of something..  a brainwave.. 

If I switch to server admin,  there is no problem..
I can do whatever I want (on that server)  

So.. the problem seems to be in the server admin account (I use) in combination with the theme.. 

Or am I assuming too much now ?

**Comment by iliajie** [comment]
> > > it's a sudo capable user
> > 
> > 
> > What is the content of the following files on your system:
> > ```
> > /etc/webmin/filemin/root.acl
> > ```
> 
> There is no root.acl file in that directory
> 
> > /etc/webmin/miniserv.conf
> 
> ....

Now I'm confused about what's going on! As it must be impossible to login to Webmin using sudo-capable user while at the same time not having in your `miniserv.conf` the `sudo=1` directive.

**Comment by Vitusware** [comment]
> Now I'm confused about what's going on! As it must be impossible to login to Webmin using sudo-capable user while at the same time not having in your `miniserv.conf` the `sudo=1` directive.

Yea, I'm brilliant 😅

Anyways.. I apperently somehow made another "root" user without being root 
and having root and sudo right on the server console. 

Mind you; There is not even a /etc/webmin/filemin/_accountname_.acl for that account I made.

This account seems to have all the rights I need to administrator the server and web-/virtual-min.
I never encountered any issues  before this one.

but there is a workaround by using the server admin, all seems to work (and nothing weird happens if I create a file or directory, as they are root:root for owner) 

still not sure why the current 'root' account can't delete a folder in filemanager with the Authentic Theme.

**Comment by iliajie** [comment]
> still not sure why the current 'root' account can't delete a folder in filemanager with the Authentic Theme.

Is there a specific folder that cannot be deleted or it doesn't work under all directories?

**Comment by Vitusware** [comment]
> Is there a specific folder that cannot be deleted or it doesn't work under all directories?

All acreoss the server the issue is the same, in webmin or Virtualmin with Authentic Theme.

![image](https://github.com/webmin/webmin/assets/29035591/d3f64228-99af-4ef0-be63-83e1df31e2e9)
But I can't delete directories.. 

Still very appreciative for your efforts..  I'm just as confused as you..

**Comment by iliajie** [comment]
> But I can't delete directories.

You should take an educated guess and provide **as more (specific) details to your system** as possible! A few reasonable questions here would be, can you delete files and cannot delete directories only, what is the directory permission set to which cannot be deleted? Does this directory even exists? Where this directory located? Is there anything logged under `/var/webmin`? The more specific information you can provide, the better!

Given the specific nature of this problem and the absence of similar reports, it doesn't appear to be a widespread issue or bug. Unfortunately, I can't dedicate further time to this without more detailed info. If you can outline the issue with detailed requirements, including screenshots and step-by-step instructions to reproduce the issue, please open a new ticket and I'll gladly take another look.

**Comment by cds-ais** [comment]
Greetings!
I have the same problem, did you find any solution?

**Comment by Vitusware** [comment]
In the end I have found: If you sign in as the server admin or server user with file manager rights  ( ie. Not Root or equivalent) you should be able to delete folders from that server. 

there should be an option in the drop-down menu ‘ sign in as server admin ‘  or similar. 
Use that and you should have no more problems. 

For some reason ‘root’ and equivalent have full server right to do anything, but something gone wrong in file manager with de delete rights regarding folders.  

Hope this explains and fixes your problem. 

Regards.

**Comment by iliajie** [comment]
> I have the same problem, did you find any solution?

Which version of Webmin do you have installed? Also, could you provide the steps to reproduce the issue?
