### ISSUE TITLE
clicks below checkboxes in file manager actually open the folder, instead of selecting it

### ISSUE THREAD

**Issue by flosb** [webmin/webmin#1146]
Tried to describe the issue better [here](http://itvolcano.com/screenshots/2019-11-23_21-01-20_2.png)

**Comment by jcameron** [comment]
@iliaross possible theme issue?

**Comment by rostovtsev** [comment]
Yes, it is theme "issue". For now, as a work around, simply hold shift while doing multi select. If you click one checkbox and hold shift, while clicking the other (few or more below) you get your multi select work.

I think it's hard to click that area that your are pointing out, but thank you for the clear bug report, I will see if that can be easily fixed.

For multi-select really use holding shift, and then click, or + on the keyboard, or * for invert select.

**Comment by rostovtsev** [comment]
Hohoho. It happened to be more than just a simple bug that you reported. I also discovered that Firefox didn't handl mentioned _hold shift + click_ for range select properly due to messed events handler.

It's all fixed now, and also your issue was addressed as well, so you can click around all checked rows to have it selected (not follow the link), and in File Manager, it will not open the folder but does nothing.

Please give it a try with the latest update (you can update the theme using its configuration page).

**Comment by rostovtsev** [comment]
@flosb Give it a try please. :)

**Comment by chris001** [comment]
> Hohoho. It happened to be more than just a simple bug that you reported. I also discovered that Firefox didn't handle mentioned _hold shift + click_ for range select properly due to messed events handler.

@iliaross 
You should file the bug you found, "_hold shift + click_ for range select messed events handler", on mozilla's firefox bug tracker ( https://bugzilla.mozilla.org/enter_bug.cgi ) and they'll fix it ASAP.

**Comment by flosb** [comment]
@iliaross updated to webmin 1.930 and Authentic installed version 19.42 with no success.
Authentic installed version 19.43-RC1 works :)
Thanks a lot for fixing this issue, it has been extremely annoying for me, should have wrote to your guys sooner :)
