### ISSUE TITLE
high cpu "/usr/share/webm"

### ISSUE THREAD

**Issue by bartplessers** [webmin/webmin#1172]
Hi,

I have 2 RPI-4 running Raspbian buster.
Both have webmin 1.940 running

#1: almost permanent +/- 30%CPU
#2: 2% CPU

![2020-01-06_15-49-48](https://user-images.githubusercontent.com/10470708/71825503-522e0300-309c-11ea-8c41-9f5e9b8a828d.png)

with the "top" command, I see that the most CPU is consumed by "usr/share/webm"

![2020-01-06_15-51-26](https://user-images.githubusercontent.com/10470708/71825632-87d2ec00-309c-11ea-83e3-b373a06744ce.png)

I have no idea why the webmin instance on the first rpi concumes more CPU.

Is there any explanation for this behavior?

kind regards,
Bart

**Comment by rostovtsev** [comment]
You might need to try to disable Real-time monitoring feature, at theme configuration.

If you have a lot of mounts, disable it for disks only, otherwise disable completely.

![image](https://user-images.githubusercontent.com/4426533/71832769-ac3ec080-30bc-11ea-971d-d81053a4183d.png)


However, it might be something else, as your screenshot with output is chomped.

**Comment by bartplessers** [comment]
Sorry for my ignorance, by I can't seem to find the above option...
Running 1.940

![2020-01-06_17-52-56](https://user-images.githubusercontent.com/10470708/71833570-7e05b480-30ad-11ea-8feb-c1e21aa64b20.png)

I have a different sidebar structure...

kind regards,
B

**Comment by chris001** [comment]
> 
> 
> Sorry for my ignorance, by I can't seem to find the above option...
> Running 1.940
> 
> kind regards,
> B

Click the icon "Webmin Themes", then click "Real time monitoring options".  Try to modify those settings.
