### ISSUE TITLE
network

### ISSUE THREAD

**Issue by alicera** [webmin/webmin#1308]
In the ubuntu18.04 ,
I set the network with /etc/network/interfaces, the final result will cause the network not work. I cant surf the internet
do you know why ?

**Comment by iliarostovtsev** [comment]
Hi,

Ubuntu 18.04+ is using `/etc/netplan` for network configuration.

Did you set `/etc/network/interfaces` manually?

**Comment by alicera** [comment]
1. Did you set /etc/network/interfaces manually?
A: yes, and the setting /etc/network/interfaces is work for ubuntu 16.04

2.
Is the webmin support for /etc/netplan ?

**Comment by iliarostovtsev** [comment]
Yes, and Webmin uses _netplan_, if it's installed.

**Comment by alicera** [comment]
if I set  the virtual network, and the webmin will not show the virtual network setting.

**Comment by alicera** [comment]
I add virtual interface, but nothing 
![image](https://user-images.githubusercontent.com/59388989/96068977-d33de480-0ecf-11eb-94be-19de8886c0e8.png)

**Comment by iliarostovtsev** [comment]
We expect you to have static IP set rather than using DHCP.

**Comment by alicera** [comment]
Do you know why?

**Comment by iliarostovtsev** [comment]
Even though such configuration doesn't make much sense, we're already supporting it.

> Do you know why?

Because you're not running latest Webmin 1.955.


**Webmin 1.955:**

![image](https://user-images.githubusercontent.com/4426533/96366212-c975e480-114e-11eb-9e79-3cadf29a42e5.png)
![image](https://user-images.githubusercontent.com/4426533/96366226-da265a80-114e-11eb-8436-cfc8a5f041e7.png)
