### ISSUE TITLE
RCE and privesc on safe user

### ISSUE THREAD

**Issue by esp0xdeadbeef** [webmin/webmin#1635]
We were RCE hunting on live stream, sorry for the poc. 
https://github.com/esp0xdeadbeef/rce_webmin
https://www.twitch.tv/videos/1483029790

Please patch.

**Comment by jcameron** [comment]
Thanks, this does look like an issue that can be exploited if the admin has created a less-privileged user manually without using Virtualmin or Cloudmin.

@iliaross this seems to be an Authentic theme-specific bug. The problem is that the code in `settings-editor_write.cgi` just takes the `file` parameter as input without doing any validation that it's one of the legit paths established in `settings-editor_read.cgi` . This is unsafe .. we can **NEVER** trust any URL parameter ever!

Also, the code in `settings-editor_write.cgi` that checks `get_user_level` won't handle the case where the user was created manually in Webmin and just granted limited access to some modules.

**Comment by chris001** [comment]
Thank you 😃   for finding this @esp0xdeadbeef !  🥂 🐮 
Please 🙏 continue, find more! 👍 🖥️

**Comment by esp0xdeadbeef** [comment]
We requested a CVE for this vulnerability this is the reference, 1267786.
Could you acknowledge this?

**Comment by jcameron** [comment]
Thanks for the CVE!

**Comment by chris001** [comment]
Is this the form that the CVE reference should be entered into?:
https://docs.github.com/en/code-security/repository-security-advisories/creating-a-repository-security-advisory

**Comment by honphilemon** [comment]
Those any one have an idea, how this can be use to customize a nuclei template for recon??

**Comment by chris001** [comment]
> how this can be use to customize a nuclei template for recon??

https://github.com/projectdiscovery/nuclei#usage

**Comment by chris001** [comment]
The [python proof of concept code](https://github.com/esp0xdeadbeef/rce_webmin) has full details on the http method and path.
However, you should probably just try to detect webmin, and the version number of webmin, and if the version number is within the range of versions which has this vulnerability, then you got a positive hit, you found one!

**Comment by chris001** [comment]
You can use [this one](https://github.com/projectdiscovery/nuclei-templates/blob/master/exposed-panels/webmin-panel.yaml) to find webmin admin login pages, but to really find a vulnerable version, you'd have to do more.
Since webmin doesn't expose its version number on the admin panel login page, AND this vuln requires the webmin admin to create a normal non-privileged user account for you, you'd either need to find a creative way to obtain the version number such as, fingerprint the exposed accessible unauthenticated public html pages and css and font library versions, compare to which versions were distributed with the vulnerable versions of webmin, to get a good guess at which version of webmin this is.  It might not be a perfect method, but it's 99% close enough and as good as you could do without further communication with the admin of that webmin server to check the actual webmin version number it's running.  This is how I'd do it.

**Comment by chris001** [comment]
FYI, they assigned number CVE-2022-30708 !
https://cve.report/CVE-2022-30708
https://nvd.nist.gov/vuln/detail/CVE-2022-30708
https://www.cve.org/CVERecord?id=CVE-2022-30708

**Comment by esp0xdeadbeef** [comment]
Thank you so much @chris001.

**Comment by iliaross** [comment]
> @iliaross this seems to be an Authentic theme-specific bug. The problem is that the code in `settings-editor_write.cgi` just takes the `file` parameter as input without doing any validation that it's one of the legit paths established in `settings-editor_read.cgi` .

Jamie, this is true, and design wise we must always treat any user input as _**un-safe**_. Although, it was assumed that a file name coming from `root` capable user is always safe. The real problem is that the validation to test whether a user is `root` capable or not _**failed**_, as the theme didn't use Webmin API before to test that.

@esp0xdeadbeef Thank you for finding this bug! For the future findings (if any), it would be preferable, if you could first contact us privately, using `security@webmin.com` and give us some time to fix the bug and release a new update. Luckily this bug is specific to a Webmin safe user, which isn't part of default configuration and must be setup first.

**Comment by jcameron** [comment]
We are releasing a new version of Webmin now that includes a fix for this issue.

@esp0xdeadbeef how would you like to be credited for this fix?

**Comment by jcameron** [comment]
Sure, I will give you credit for the find!
