### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by muxcc** [webmin/webmin#1638]
apt update

Ошб:6 https://download.webmin.com/download/repository sarge InRelease
  Не удалось соединиться с download.webmin.com:443 (104.207.151.13)

**Comment by chris001** [comment]
Sorry, however this free vpn "cloudflare warp" for linux server (command line), should enable your server to download the updated version.
https://blog.cloudflare.com/announcing-warp-for-linux-and-proxy-mode/

**Comment by muxcc** [comment]
Warp did not help .. since it's not really vpn, but more CDN..it does not mask IP (RU)
```
[root@xlam:~]# curl -I https://download.webmin.com/download/repository/dists/sarge/
HTTP/1.1 403 Forbidden
Date: Sat, 21 May 2022 15:27:27 GMT
Server: Apache
Content-Type: text/html; charset=iso-8859-1
```
VPN with geolocation in germany (DE) helped
```
[root@xlam:~]# curl -I https://download.webmin.com/download/repository/dists/sarge/
HTTP/1.1 200 OK
Date: Sat, 21 May 2022 15:28:00 GMT
Server: Apache/2.4.6
Content-Type: text/html;charset=ISO-8859-1
```
**_I mean, why do this - block updates for Russian users ..._**

**Comment by chris001** [comment]
@muxcc I think it's not webmin website blocking any countries.  I think the network interconnection provider, which has disconnected the fiber connection and suspend or cancel some RU fiber accounts, because payment is not possible because EU banks are blocked from receiving electronic funds transfer (swift online bank payment system) from RU customers.  Sorry, and am glad with the Germany IP VPN you've updated.

**Comment by swelljoe** [comment]
Yeah, we've made no changes that prevent access from anywhere. If we thought it might help people in Ukraine in any way for us to do so, we would, but individuals in Russia using our open source software isn't going to alter the course of the war.

Ilia, one of the primary developers of Webmin and Virtualmin is Russian (though he left due to the war, as we wouldn't have been able to pay him, otherwise). We have nothing against Russian citizens and have done nothing to prevent your access.
