### ISSUE TITLE
Upgrade to 1.995 on Ubuntu & Debian fails

### ISSUE THREAD

**Issue by TheBudda** [webmin/webmin#1675]
A little heads-up! I think you got a bug! Just done an upgrade to 1.995, via webmin, the upgrade fails lost connection and webmin stopped working

I had to run sudo dpkg --configure -a to fix it! Please see screenshot

![webmin_update01 07 2022](https://user-images.githubusercontent.com/16983376/176877080-880fdf31-ff6d-4845-b0a8-53ded88a007b.png)

**Comment by iliajie** [comment]
Damn, I'm afraid you're right! 😞 

`makerpm.pl` and `makedebian.pl` call `/etc/webmin/stop` which in turn call `systemctl stop webmin`. I cannot believe I missed that! 

Thanks for a report.

**Comment by TheBudda** [comment]
> Damn, I'm afraid you're right! disappointed
> 
> `makerpm.pl` and `makedebian.pl` call `/etc/webmin/stop` which in turn call `systemctl stop webmin`. I cannot believe I missed that!
> 
> Thanks for a report.

You are very welcome. Happy to always help

**Comment by jcameron** [comment]
@iliaross why does `systemctl stop webmin` kill Webmin when upgrading via the UI when we have have this code to prevent the process from being killed by a signal? https://github.com/webmin/webmin/blob/master/package-updates/update.cgi#L45

**Comment by iliajie** [comment]
Because default `systemd` kill mode (alternatively set with `KillMode=`) is `control-group` and running `systemctl stop` will completely stop all remaining processes in control group (including the main process). The work around for us could be is to set `KillMode` to `none` but `systemd` documentation advises _strongly against_ doing that.

Now, as you fixed `miniserv` bug before, restarts will work correctly in all cases and sending _SIGHUP_ will work rock solid with all `systemd` versions.

---

Moreover, after thinking more about this problem and doing additional tests, I think I will change my **PR** to _always_ send _SIGHUP_ on update, meaning that we must be able to restart even older versions of Webmin and make transition smooth.

My initial extra precaution potentially would  cause more issues, as even though sending _SIGHUP_ on the older versions of `miniserv` changes _PID_ it really shouldn't crash Webmin in most case scenarios.

**Comment by jcameron** [comment]
@TheBudda which Webmin version were you upgrading from? 

Also, which Debian or Ubuntu version are you running there?

**Comment by TheBudda** [comment]
> @TheBudda which Webmin version were you upgrading from?
> 
> Also, which Debian or Ubuntu version are you running there?

@jcameron webmin 1.994 Ubuntu 22.04

**Comment by jcameron** [comment]
I think we've nailed this down, and we're releasing Webmin 1.996 now that will fix this issue..

**Comment by TheBudda** [comment]
> I think we've nailed this down, and we're releasing Webmin 1.996 now that will fix this issue..

How mad is this? I just upgraded to 1.996 with no issue :- )

**Comment by chris001** [comment]
Had a failed install of `webmin 1.995` on Debian 11.  
The failed install of `webmin` was blocking all other package updates from installing.
To resolve, had to run command:
`sudo dpkg --configure -a`   then it completed the install for `webmin`, `usermin`, etc, and then, other package updates installed.

**Comment by jcameron** [comment]
@chris001 did you see any issues upgrading to 1.996 ?

**Comment by chris001** [comment]
@jcameron No issues, all good upgrading to 1.996 !
