### ISSUE TITLE
File Manager: stuck on load

### ISSUE THREAD

**Issue by didaxRedux** [webmin/webmin#1729]
Hi,
the other day I opened a folder (plenty of files!) with file manager.
After viewing the folder, I logged out directly from webmin.
Today, by opening the webmin again and accessing the file manager, I remain fixed during the loading phase with cpu at 100%.
I suspect that the system is recovering the last visited path and therefore gets lost in some onerous operation.
Is there a way to manually delete the last visited path and unlock the file manager?

**Comment by iliajie** [comment]
> I suspect that the system is recovering the last visited path and therefore gets lost in some onerous operation.

It was a bug and was already fixed with all latest patches to the [file manager](https://github.com/webmin/webmin/commit/ed4cea53236197faf54ab35dfe2765a2835abb42) and the theme 20.01-RC3 pre-release version.

Meanwhile, to work around the issue use right side slider or theme configuration page to clear cache. You could also apply mentioned patch (if you're capable) and install latest pre-release version of the theme to see if the issue is getting resolved for you.

**Comment by didaxRedux** [comment]
Thank you very much Iliajie... solved!

**Comment by iliajie** [comment]
Fantastic! I am glad it was solved for you! Thank you for reporting!
