### ISSUE TITLE
Adopt/Deliver Authentic Theme as a bundle

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#183]
Jamie, I would like to propose to deliver [Authentic Theme](https://github.com/qooob/authentic-theme) as part of Webmin package. It's quite mature to deliver better user experience.

What do you think?

**Comment by jcameron** [comment]
I could certainly support that - how about if it was part of the next release, as an optional theme?

**Comment by qooob** [comment]
That sounds great! Please also be kind telling me, what is missing/needed to make it default theme. 

I will try to embody all your points.

I'm about to release by the end of the week or earlier the updated version (With Alt+S key placeholder instead of that crazy Mac sign + small tweaks).

**Comment by swelljoe** [comment]
We're not saying it won't become the default. Just not in the next release. There are a few things I'd like to see (though even with these, I think we need to deploy it in stages as Jamie suggested, with it being shipped with, but not default, at first, for reasons I'll talk about below).

The Virtualmin/Cloudmin menus need to work, which we know you've got coming (and the bits in the Virtualmin and Cloudmin menu that include those need to be disabled using the right global variables, I can help you with that).

Some other things I think should be added to the theme:

1. Sections for module configuration, particularly for Virtualmin (see my new theme and the Virtualmin Framed Theme for examples of this in action).

2. I still don't really like the "big list of links" layout in modules that have an icons_table. Like Apache, Postfix, and BIND. I understand not loving the current icons, but we could potentially drop those in favor of Tango icons (I doubt there is another icon set that is large enough to cover most of our requirements...though I can make new icons from existing ones, usually, and did make a few dozen of the icons in the old icon set, based on components from the Nuvola icon set by David Vignoni).

Font Awesome might even have most of the icons we need...but I wouldn't bet on it. It seems much more consumer and mobile focused than our needs. If we find a good icon set, we can use the SVG versions, most likely. I think SVG is well supported by all of the browsers we need to support now, but would need to check. Another option might be buttons instead of links, the way you did the links rows (those are great!), and putting them into a some sort of columnar layout (see icons table my theme for a responsive column layout that scales up and down nicely).

3. I'd probably like to see the donation link that's currently on the System Information page get nixed, as well. Though I obviously want you to get paid for your work (and will continue to send you donations on the regular, as long as you're actively maintaining the theme, and have no problem linking to your github in a less over way/location, and encouraging donations and contributions in almost any other way).

But, mostly, I think, we just need some testing in a very wide array of settings before making it the default. Webmin likely has a million+ installations. We can't just drop a major change like this on folks without some time for people to get used to it, even if it is clearly superior (which I think we all agree that it is). Jamie and I discussed a time line for this theme, and it's entirely plausible it could be the default in the release after next, or at worst the release after that (so, 1.760 at the latest but probably 1.750) and for the entire life of Webmin 1.x after that (and, I'd like want to help you port your theme to Webmin 2.x when that gets forked, but it will be six months to a year before we start shipping Webmin 2.x to users for production use, so Webmin 1.x is the "real" Webmin for most of 2015).

That's where my head's at on this one, and I think Jamie's roughly on the same page, based on our conversation a few days ago. We'll be meeting with Eric on Thursday to discuss this and other stuff, and we'll probably firm up more details on how Webmin releases will be scheduled in the run up to 2.x being forked.

I may make some pull requests in the next few days, of stuff I think should change, though you're free to merge them or not, based on your own taste and preferences. I feel pretty strongly that *something* needs to change about the icons tables, but I'm not super committed to what it ought to look like.

**Comment by qooob** [comment]
Alright, sound good and makes a lot of sense in general!

Before I continue, with answering to your points, please let me to let you know, that just today, I have found a way (algorithm) for completely fixing drawbacks of all possible modules in Webmin, meaning, there are a lot of places in modules, where table borders (lines) are not visible due to _wrong amount of cells_, generated by the module. For example, a `<table>` has `<tr>`s and some `<tr>` has 3 `<td>`s and some has 5 `<td>`s - that create a lot of problem starting from missing lines (borders) on tables to not working __dataTables__, as it requires perfectly accurate table structures. Anyway this is fixed with simple implementation, that was tested around and showed great results. 

I will add this functionality in couple of days, _so please wait till that_, before making pull request as I'm going to also change some Perl part for your icon proposal part (talk about it later).

Here is the piece of code that I come up with today to make those tables look perfect. Example, can be tested, for instance in `Webmin->Backup Configuration Files`, now if you go there, there are a lot of mess with table drawings. Here how it works, take a look and think if it might cause possible problems (which I really doubt, as so far - it's literally perfect). JS part for tables, should be fired when DOM is ready:

```javascript
// Fixing tables with wrong number of cells
$.each($('table tbody'), function() {
    var c = $(this).children("tr"),
        b = [];
    $.each(c, function() {
        b.push($(this).children("td").length)
    });
    var a = Math.max.apply(this, b);
    $.each(c, function() {
        var e = $(this).children("td").length;
        if (a != e && !$(this).find('hr').length) {
            for (var d = 0; d < (a - e); d++) {
                $(this).append("<td></td>")
            }
        }
    });
    console.log("Table(s) fixed...");
});

// Remove empty <tr> tags
$.each($('table tr'), function () {
	if ($(this).is(':empty')) {
		$(this).remove();
	}
});

// Remove colspans attr, if no hr inside
$.each($('table td'), function () {
	if (!$(this).find('hr').length) {
		$(this).removeAttr('colspan');
	}
});
```

Alright, now about the rest of things. 

1. Yes, I think I would like to have some help about left menu generation and hiding right part for Virtualmin/Cloudmin modules, as my knowledge in Perl very low (<5%) (I think..). If there is no help, well no problem I will figure out at one point but it might take a bit more time.

2. About the icons - alright, I will make an `.options` file, which will be possible to chose for users, whether  they want to have icons or prefer just to have links (like I do, at least so far :) ). I liked Tango icons and will try to merge them in soon enough. The problem about it is that I would like someone to build an associative array of iconName => [trigerName1,trigerName2, trigerName3, trigerName4 ... ]. So later, it would be easy to iterate through them, assigning need icon for each link.. This work is very easy but very annoying..

3. I will remove donation button from on hover event but will leave the link to GitHub and modal popups upon updates. Did you see the one by the way? (the one with Changelog and details, that pops up right after installation/update - I would strongly like to keep it..)

**Comment by swelljoe** [comment]
I've been gradually trying to fix the bad HTML markup at the source. I've got a test harness made to test the HTML validation of cgi scripts in Webmin, though it's proving difficult to use because many scripts are full of strict/warnings problems, in additional to HTML validation errors, which makes it harder to check HTML validation. 

I'll pull the latest git revision and see about making the left menu code work for your theme. If it's going to take you a long time to figure it out, I'd rather tackle it for you, since I can probably have it working in an hour or so. That way you can spend your time on other things.

As for icons, themes can provide custom icons without needing to override anything via code or an associative array or anything. You just create a directory for the module, and drop new icons into the "images" subdirectory. We could also do it at the root Webmin level, though I'm hesitant to embark on such a major change in the 1.x branch. Since we're going to be removing so many icons in the 2.x branch, it would require a lot of work that will no longer be relevant in six months or a year. But, if we do it now in Authentic and then do it again for Webmin 2.x, that will also be wasted work. Maybe I should talk to Jamie about solving this in a way that allows easier replacement of icons (like adopting the Free Desktop Icon naming guidelines for Webmin icons...so we could simply drop a Gnome or KDE icon them into place, somehow, and have it Just Work). Icons are time-consuming enough in Webmin that major changes have happened very, very, very rarely. I've done it twice in the 15 years I've been working on Webmin-related stuff. Both times took approximately forever. If we could double that time and make it so we never have to do it manually again, that'd be a win, I think. Will talk to Jamie about it.

I like the modal popup a lot! I think we'd like to use that for the "What's New" display in Virtualmin, too. And, yes, you can certainly include links to your github and such. We don't want to strip your identity from the theme; just want to be more subtle about donations (we don't have donation requests in any of our stuff either). Our goal, also, is to channel people who want to spend money with us into a product direction, which provides us a renewable source of revenue and hopefully allows us to commit to supporting ongoing development for years to come.

**Comment by qooob** [comment]
Joe, alright! I will publish the updated version of the theme today or max tonight. It will be more precise release ever made (UI wise - everything should be straight, aligned and so on).

After that I will focus on your pull requests and updates for the left side and etc. Just comment out my old parts of the code and place yours - it will be easier for me.

I will also remove donation button from seeing on every day basic.

Then icons part I will put off then for later and will make it optional in the future. Probably those/some users that use Authentic Theme without icons already got used to seeing it without them. Besides probably we/you should think of third/fourth possible option instead of having/not having the icons. Probably there is better solution that would beat idea of having/not having icons in general.

You can trick W3C validator, if this is the case. In `karateka.org` you can see this :) . The problem is that if you open my sites in browser you will get all of those `og:title, og:description, og:*` meta tags. Because Facebook wants them, Google+ wants theme and Tweeter too but W3C. So when validator goes to check my page it gets the properer HTML (yes it's required) BUT it doesn't get to see meta tags, which are perfectly valid but which it doesn't support at the moment. - Everybody is happy. W3C and Social Networks and most importantly me! :D Just try to paste into W3C directly from my page (any) and later validate the same page using a link. Oh, by  the way, `user_agent` for W3C contains `W3C_Validator` - the rest is obvious.

**Comment by d19dotca** [comment]
Just wanted to say that I fully support this idea too! :+1: 

@iliaross  - your work on Authentic has been amazing, kudos! I will be having more free time in the coming months so I will be donating some time to resolving some of the more minor issues / tweaks to be made in the future, as I'm an avid web developer and hope to offer even the smallest of assistance to the project. 

And everyone's work on Webmin has been amazing too, this is by far the best most comprehensive web admin panel (for free) that I've experienced so far. Keep up the amazing work!

**Comment by qooob** [comment]
@dustindauncey, thanks pal!!

**Comment by qooob** [comment]
Jamie, how about also adding it to the demo version of Webmin, that is running on `http://webmin-demo.virtualmin.com/`?

**Comment by iliaross** [comment]
Alright, my friends! Authentic Theme 10.0.0 is out. 
It's most thoroughly worked on release in terms of details and final testings.

I think the theme is ready to go!? I would be very happy to see my work as part of such amazing package such as _Webmin_.

**Highlights of version 10.0.0 (Mar 4, 2015):**
- Changed theme **repo location** to _GitHub_
- Improved left menu design to be more flat-like
- Improved the look of old **ui_hidden** collapse, to look more like new _Bootstrap_ collapse
- Added support for **Webmail** in _Usermin_ [#104](https://github.com/iliaross/authentic-theme/issues/104)
- Added **dataTables** search, in case table contains more than 10 rows
- Added **dataTables** on filesize, to properly sort columns containing filesize data [#103](https://github.com/iliaross/authentic-theme/issues/103)
- Added **custom logo** support for login screen [#116](https://github.com/iliaross/authentic-theme/issues/116)
- Added support for **basic settings** to control the theme (disable loaders and more)
- Added extended controls to _System Information_ page for **ConfigServer Security & Firewall**
- Added complete support for scrolling on _iPhone/iPad_ [#115](https://github.com/iliaross/authentic-theme/issues/115)
- Fixed server-side search that stopped working after adding _autocomplete_
- Fixed **select** issue in _Internet Explorer_ browser [#99](https://github.com/iliaross/authentic-theme/issues/99)
- Fixed package updates showing wrong numbers on _System Information_ page [#112](https://github.com/iliaross/authentic-theme/issues/112)
- Fixed **quotas charts** issue, displaying incorrect numbers in _System Information_/_Quotas_ [#110](https://github.com/iliaross/authentic-theme/issues/110)
- Fixed missing left menu reload upon importing new virtual server
- Fixed stuck loader appearing in certain cases [#117](https://github.com/iliaross/authentic-theme/issues/117)
- Fixed stuck loader in all third party modules, like **AWStat, Webminstat** and **OpenVPN + CA** [#106](https://github.com/iliaross/authentic-theme/issues/106)
- Fixed **hotkeys triggers**, which now is executed only in case the switch is not already active [#118](https://github.com/iliaross/authentic-theme/issues/118)
- Fixed fatal error happening when changing domain in _Webmin/Virtualmin_ domain owner mode
- Fixed **System Statistics** link to be shown only in administrative mode
- Fixed _Virtualmin->Administration Options->Switch To Server's Admin_ link, being opened in `__parent` window
- Fixed **WYSIWYG bar** being _lower_ than it should be from the upper border, when composing new message
- Fixed login page throwing an error to the console
- Removed screen-saver, as it was eating a lot of memory

Thank you all and _enjoy_!!

**Comment by jcameron** [comment]
Awesome - I plan to include this in the next Webmin release, by checking out the most recent version of your theme from Git.

**Comment by jcameron** [comment]
Well, I'd like to... but running git clone https://github.com/iliaross/authentic-theme.git fails with "fatal: https://github.com/iliaross/authentic-theme.git/info/refs download error - "

**Comment by jcameron** [comment]
Never mind, turns out my Git version was too old. 

Which repo and directory should I check out to get a version of the theme for inclusion in Webmin? The one from https://github.com/iliaross/authentic-theme seems to be missing the #! lines at the start of the .cgi scripts.

**Comment by iliaross** [comment]
Thanks, Jamie! Yes, `https://github.com/iliaross/authentic-theme` or just unpack `authentic-theme-latest.wbt.gz` and use it.

About "missing" `#!/usr/bin/perl`, well, theme is spawned under _Webmin_ and using those directives seems pretty useless because of that. Besides it's autodetected in most cases and different in NIX/Windows environments.

Moreover and most importantly, it has _never ever_ caused an issue for anybody.

**Comment by jcameron** [comment]
You're right that the #!/usr/bin/perl line isn't strictly needed as Webmin runs the CGI scripts for the theme within the perl webserver process. However, miniserv.pl does look for those lines - so it would be easier for me to test and package your theme if all the .cgi scripts in Git started with #!/usr/bin/perl . 

This will get replaced with the correct path for the target system and packaging or install time though.

**Comment by qooob** [comment]
Alright, will do in few hours!

**Comment by qooob** [comment]
Alright, all set! Please take a look when you have time, I think it's all correct!

**Comment by jcameron** [comment]
Ok, I tried this out on one of my older systems and I noticed a couple of problems :

1. In some .cgi scripts you call version->parse, but this "version" perl module is never loaded. 

2. All the .cgi scripts have Windows-style \r\n newlines at the end .. this shows up when editing them in vim. There's no actual impact from this, it just looks odd when editing the file :-)

**Comment by qooob** [comment]
I will check at my text editor that I have Linux like line endings, I though I did..

About `version`.. It's external Perl module to parse versions.. Or you saying I forgot to state `use version` before that? ;)

**Comment by jcameron** [comment]
Yeah, I didn't see "use version" anywhere in your code.

**Comment by qooob** [comment]
Alright, forgotten it, I think. Will fix it shortly, when get to PC.

**Comment by qooob** [comment]
Fixed it, please be kind talking a look.

**Comment by sgrayban** [comment]
Can't you use dos2unix to convert MS EOL to unix EOL ? I do this often and its just as fast or faster then loading it then saving as a unix EOL

**Comment by qooob** [comment]
Yes, I'm fixing line endings now.. I use Linux and not sure where those came from.. I remembered fixing that after I made a commit about missing `use` declaration..

**Comment by qooob** [comment]
Alright, also fixed line endings. @sgrayban Thanks, Scott!

**Comment by jcameron** [comment]
Great, thanks!

**Comment by jcameron** [comment]
BTW, I noticed that in modules like Network Configuration no icons show up on the first page, just titles .. is that intentional?

**Comment by qooob** [comment]
Yes, Jamie! All icons were removed intentionally. We had this discussion with Joe already.

**Comment by jcameron** [comment]
OK, cool .. just checking that this wasn't due to some install error on my part.

**Comment by qooob** [comment]
are planning to put it to distro already? I have small bug fixes.. Could you wait a bit, please?

**Comment by jcameron** [comment]
I was going to build a devel version of Webmin today that includes your theme, but I can wait a bit if you have pending bugfixes.

**Comment by qooob** [comment]
That would be great! Thanks! I will notify you right whenever I finish but it will be max in 24 hours.

**Comment by qooob** [comment]
Jamie, alright! I'm done. Version 10.1.0 is out. Please be kind looking at new `__settings()` at `authentic-lib.cgi`. It works very well from what I tested. Please tell me if it's alright?

**Comment by jcameron** [comment]
That looks OK, although having the settings file in JS and parsing it with perl regexps seems a bit odd.

**Comment by qooob** [comment]
:) OK. I will later, maybe, add configurable settings using UI. It's, odd a bit, I agree but in this case I can use them `here and there`.

**Comment by jcameron** [comment]
Cool - I've uploaded a new 1.733 devel version of Webmin that includes your theme, and added a new item on http://www.webmin.com to let people know about it.

**Comment by qooob** [comment]
Awesome! Thanks! :D

**Comment by qooob** [comment]
Jamie, there is no reason to include `authentic-theme-latest.wbt.gz`, just extra 2.4MB of data! ;)

**Comment by jcameron** [comment]
Good point - maybe that file could be put in a separate directory in your repo, rather than being in the same directory as the theme source?

**Comment by qooob** [comment]
Does it make any difference for you to `--exclude` a file or directory? You could do it using `.git/info/exclude` but you already know it, I think.. If it makes any difference, than I could create a separate repo for doing that in case you really need this?

**Comment by jcameron** [comment]
Sure, I could do that - however, it seems a little odd to have the wbm.gz file included as part of the repo. It would be almost like including a binary in a source repository.

**Comment by qooob** [comment]
Alright, it makes sense! I will move links next time and complitely remove it in few releases, so there would be no broken links.

**Comment by qooob** [comment]
Jamie, I have moved build file to directory `.builds`, please take a look. I will remove the file from the root folder only later, when time goes by, so there would be no broken link issue.

Thanks for advising, it's indeed better and also helped me clear different parts of my project.

**Comment by jcameron** [comment]
Great, thanks!

**Comment by qooob** [comment]
Jamie, please be kind pulling new, updated version of Authentic Theme 10.1.2 before releasing. So far there is a version 10.1.0 in pre-package.

**Comment by jcameron** [comment]
Sure, I will sync before releasing the 1.740 version of Webmin.

**Comment by jcameron** [comment]
One more question - is your theme also ready for inclusion in Usermin?

**Comment by qooob** [comment]
Yes, perfectly it even supports webmail, so it could be also included into usermin-webmail. Please test it yourself and tell me what you think? :)

**Comment by jcameron** [comment]
Looks pretty good - I will include it in the next Usermin release too.

One minor thing though - the default mode on the left menu after logging in should probably be "Mail", if available.

**Comment by qooob** [comment]
Ohh. OK. When you plan to release new version?

**Comment by jcameron** [comment]
Could be a couple of weeks - let's see what issues users turn up with the theme in Webmin first.

**Comment by qooob** [comment]
Alright. I will also make sure that the theme has no dependencies.

**Comment by qooob** [comment]
Alright, after logging in to Usermin, a user will be taken to Mail, in case the module is available. Thanks for the idea!

**Comment by iliaross** [comment]
Jamie, hi! ;) I just updated to the new version 11.00.

Features I was talking about in the other thread, like notify admins on successful login/landing is supported now by the theme. It can send messages to selected users/emails (upon Webmin/Usermin login/access to login page by unauthenticated users) and also has a whitelist of IPs, so not to be noisy.

I have fixed all possible bugs I could find and those that people posted. I also removed all dependencies, so theme will just work out of the box on any system.

Added window automatic scrolling, upon page is populated from server-side. In settings added the ability to disable the theme notification updates and many many more. You can read about all changes here: https://github.com/iliaross/authentic-theme/blob/master/CHANGELOG.md

In my opinion the theme is ready to become the default one as never before.

Best regards,
Ilia.

**Comment by jcameron** [comment]
Cool, looks good. I have to be pretty cautious about changing the default though, as there are a lot of Webmin users out there.

**Comment by qooob** [comment]
Please test it thoroughly. I think it will be much better for Webmin image to have contemporary look/usability as such. Non of the todays panels (including those you have to pay for), even close, come with such interface. You will not lose old users. Those don't like the new theme can easily change back to the old/preferred one but new users should be caught from the first start, as they might not even know/want to change the theme. With changing all *min sites to contemporary look as well, you should definitely be at the top of all server panels.

:) to make all I've said in one phrase - it's time to move on..

**Comment by swelljoe** [comment]
I think we all agree on moving forward. But, Jamie's right about proceeding with caution. A million users is a lot to surprise with a major UI change. So, we've gotta really test it hard. At the very least, I need to make sure that users using screen readers are able to switch to another theme if this one is unusable for them. (It'd be ideal if they could use this theme effectively, but I'll need to do a lot of testing for that...but, the fact that there is a change theme button on every page in the left menu makes the minimum likely to be feasible already, but I will need to test.)

**Comment by qooob** [comment]
Alright, no doubts about that! Whatever is good for the project and for the people is also good for me. Let me know if you find issues - I will fix it.

**Comment by qooob** [comment]
Jamie, why not deliver Authentic Theme in Usermin and Usermin Webmail packages? The packages above could simply have a `symlink` to Webmin installation.

You could have a check in post install scripts of those packages, that would either put a `symlink` to `.../webmin/authentic-theme` or have complete package written to its directories in case Webmin is not installed.

Version 11.55 is completely supporting pretty much everything and in every __*min__ package!

**Comment by jcameron** [comment]
Yes, it will be included in the next Usermin & Webmail releases.

**Comment by qooob** [comment]
Alright, super! :)

**Comment by qooob** [comment]
Alright, a lot of work has been done on icons. Version 12 of the theme now supports long waited icons. Old way of displaying only links is also optional and available.

Shortly, there are 3 types of displaying icons. 1. Is Default (Big Icons); 2.Small Icons with tooltip (my favorite) and x-small icons. You can read in change log of how it works and how to control it.

For the future, Joe, I have made the theme automatically detect `.svg` icons. Just when ever you finish your icons, we'll just drop all of them to the module folder, same way but with `.svg` extention and _Authentic Theme_ will automatically detect it. I will wait for SVG icons from your side. So far, old icons look not that bad. There were some missing icons for some modules, so I have made a patch (to make sure that browser doesn't get 404 error) and replaced it with SVG icon, saying `ICON NOT FOUND`. You can see it in action by your self.

Please let me know more, if the way I made icons to work, makes satisfies you guys!?

Regards,
Ilia

**Comment by qooob** [comment]
Welcome to the new age! ;)

![1](https://cloud.githubusercontent.com/assets/4426533/7446510/9bfaa9a4-f1e3-11e4-92f8-3a245325b063.png)
![2](https://cloud.githubusercontent.com/assets/4426533/7446509/9bf84d4e-f1e3-11e4-9c1d-7db0733ed5a9.png)
![3](https://cloud.githubusercontent.com/assets/4426533/7446508/9bf6f336-f1e3-11e4-8351-6986afb0368a.png)
