### ISSUE TITLE
It appears that "-G" could be passed as an argument to 'pdbedit'

### ISSUE THREAD

**Issue by farglabs** [webmin/webmin#1894]
https://github.com/webmin/webmin/blob/3f322bee84016589770812f30aad5ebfea009c46/samba/samba-lib.pl#L649

This would throw an error.

**Comment by martelrotschy** [comment]
It appears that the `-G` worked the same as `-g` in an older version of pdbedit (even though the docs  never included G as a valid option).

I confirmed that this is broken with pdbedit version 4.15.13-Ubuntu, but worked on version 4.13.14-Ubuntu.

Since it was never in the docs, I am not going to open an issue for samba-common utils.
