### ISSUE TITLE
Module Request: Prosody XMPP Server

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#190]
Jamie, hello! ;)

I would like to recommend and ask (if possible) for support of [Prosody XMPP Server](http://prosody.im/). It's awesome - powerful and simple to setup at the same time, reliable and updated recently. It would be very good if _Webmin_ could provide support for it too!

Regards,
Ilia

**Comment by jcameron** [comment]
That's a pretty good case for a module, but unfortunately I don't really have time to write it right now. And since I don't use Prosody myself, it's not high on my priority list. 

Minecraft on the other hand ... :-)

**Comment by qooob** [comment]
I understand! :D Alright! Maybe I will one day.. ;) Sorry for disturbance!

**Comment by swelljoe** [comment]
What's the format of the configuration file(s)? I've been working (half-assedly) on a module to automatically parse and produce a UI for any INI file. I also tinkered with TOML. It's pretty easy to wrap up a basic UI if there's a decent Perl module for the configuration file format, though it won't necessarily be a powerful and comprehensive module.

**Comment by qooob** [comment]
It's cool.

Here is the [example](http://prosody.im/doc/example_config) of the config file.

**Comment by mbnoimi** [comment]
@jcameron For give me for this silly question:

Why "Jabber IM Server" module exists if it's unable to admin XMPP server such as Prosody?!

**Comment by mbnoimi** [comment]
As you know the most used XMPP servers are:
1. ejabberd
2. Prosody
3. Openfire

**Comment by swelljoe** [comment]
Jabber IM Server module predates all of those XMPP servers. I think ejabberd is the subsequent project that came after the original and shared some code, maybe? I don't really follow XMPP development closely (and Jamie doesn't either, obviously!). It's been many years since Jabber IM Server module was a thing that'd be usable (it shouldn't still be in Webmin core; if it hasn't already been removed, I''ll ask Jamie to remove it).

Ilia, that example config is written in Lua, which is not so easy to parse (it, I guess, effectively requires Lua to parse it completely). It'd be extremely non-trivial to make a comprehensive editor for the config file, unless it really limits itself to just those structures in the example provided (it seems like it could contain arbitrary Lua code, since the example of checking it does a generic lua syntax check, rather than some more specific validation).

**Comment by qooob** [comment]
I agree, Joe. We could start from `start`, `stop` and `restart` at the top of the table and `Edit Configuration` manually button. The rest could be added later. Prosody is cool and getting more and more popular. It's in distros already (at least Fedora).

**Comment by mbnoimi** [comment]
It's really silly approach to set the configurations of Prosody in ```Lua``` while they can use ```.config``` or ```.ini``` format so I don't blame ```Webmin``` guys in case they decided to delete their XMPP module.

Both ```Openfire``` and ```ejabberd``` have web interfaces for the administrators while ```Prosody``` hasn't! This issue related to ```Prosody``` community but if ```Webmin``` guys decided to support ```Prosody``` silly config file it will increase the popularity of ```Webmin``` and ```Prosody``` all together because the administrators haven't other choice rather than ```Webmin```

**Comment by marclaporte** [comment]
My team and I are looking into XMPP solutions.

About Webmin vs Virtualmin: When we create a user in Virtualmin, we have options for email, FTP,  etc. Ideally XMPP is added to this list. Given Virtualmin is designed to manage multiple domains and projects, it makes sense to use a multi-tenant XMPP server, which excludes Openfire:
https://igniterealtime.atlassian.net/browse/OF-162?focusedCommentId=16286

Prosody is multi-tenant and a fine choice. There are others as well.

**Comment by iliajie** [comment]
Hello Marc!

Currently, it wouldn't be a problem to use a **Command to run after making changes to a server** to create/delete/modify a Prosody user.

I personally really like XMPP, and I expect it to grow in popularity over time, considering what large corporations do with user data.

We need to discuss this with Jamie and Joe over again. I think having an additional accordion to handle XMPP/Prosody users and a separate button to add XMPP/Prosody user in **Edit Users** page wouldn't be out of line, considering that we already handle various types of users like database and webserver users.

It could technically be built into Virtualmin (even though it’s a questionable/moot point), or it could definitely be handled via a standalone module.

The most likely right solution is to handle it via a separate Virtualmin module.

**Comment by jcameron** [comment]
Yeah I woudn't be in favor of adding Prosody user support to Virtualmin core, but this could totally be added via a plugin..

**Comment by marclaporte** [comment]
Understood. We'll come back to you in 2-3 months with a proposal.
