### ISSUE TITLE
Webmin on Fedora38 cannot update to v2.100-1

### ISSUE THREAD

**Issue by mollcons** [webmin/webmin#1974]
I am running Fedora38 and I tried to update Webmin (in the browser) to v2.100-1 as suggested and having downloaded the update (twice now) received the following error:

/tmp/.webmin/621664_676094_2_upgrade.cgi.rpm:error: Verifying a signature using certificate 1719003ACE3E5A41E2DE70DFD97A3AE911F63C51 (Jamie Cameron ):
  Key D97A3AE911F63C51 invalid: not signing capable
error: Verifying a signature using certificate 1719003ACE3E5A41E2DE70DFD97A3AE911F63C51 (Jamie Cameron ):
  Key D97A3AE911F63C51 invalid: not signing capable
 digests SIGNATURES NOT OK
 
 Why is this suddenly occurring? And how do I manage the update?

**Comment by iliajie** [comment]
Hello,

Try running ti fix the problem:

```
wget https://raw.githubusercontent.com/webmin/webmin/master/setup-repos.sh
sh setup-repos.sh
```

**Comment by mollcons** [comment]
Still will not update:
/tmp/.webmin/58542_678954_2_upgrade.cgi.rpm:error: Verifying a signature using certificate 1719003ACE3E5A41E2DE70DFD97A3AE911F63C51 (Jamie Cameron ):
  Key D97A3AE911F63C51 invalid: not signing capable
error: Verifying a signature using certificate 1719003ACE3E5A41E2DE70DFD97A3AE911F63C51 (Jamie Cameron ):
  Key D97A3AE911F63C51 invalid: not signing capable
 digests SIGNATURES NOT OK

**Comment by iliajie** [comment]
First of all try running `dnf clean all` first.

Also, what is the output of:

```
grep -Rsi webmin. /etc/yum.repos.d
```

**Comment by mollcons** [comment]
Output is:
/etc/yum.repos.d/webmin.repo:[webmin-noarch]
/etc/yum.repos.d/webmin.repo:name=Webmin - noarch
/etc/yum.repos.d/webmin.repo:baseurl=https://download.webmin.com/download/newkey/yum
/etc/yum.repos.d/webmin.repo:gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-webmin-developers

Then (after running dnf clean all I attempted the update which generated the following:
/tmp/.webmin/500000_681302_2_upgrade.cgi.rpm:error: Verifying a signature using certificate 1719003ACE3E5A41E2DE70DFD97A3AE911F63C51 (Jamie Cameron ):
  Key D97A3AE911F63C51 invalid: not signing capable
error: Verifying a signature using certificate 1719003ACE3E5A41E2DE70DFD97A3AE911F63C51 (Jamie Cameron ):
  Key D97A3AE911F63C51 invalid: not signing capable
 digests SIGNATURES NOT OK

**Comment by iliajie** [comment]
Alright, and what is the output of:

```
rpm -q --queryformat "%{SUMMARY}\n" $(rpm -q gpg-pubkey)
```

**Comment by mollcons** [comment]
rpm -q --queryformat "%{SUMMARY}\n" $(rpm -q gpg-pubkey)
Fedora (35) <fedora-35-primary@fedoraproject.org> public key
Google, Inc. Linux Package Signing Key <linux-packages-keymaster@google.com> public key
RPM Fusion free repository for Fedora (2020) <rpmfusion-buildsys@lists.rpmfusion.org> public key
Fedora (36) <fedora-36-primary@fedoraproject.org> public key
Jamie Cameron <jcameron@webmin.com> public key
RPM Fusion nonfree repository for Fedora (2020) <rpmfusion-buildsys@lists.rpmfusion.org> public key
Skype Linux Client Repository <se-um@microsoft.com> public key
Fedora (37) <fedora-37-primary@fedoraproject.org> public key
Google Inc. (Linux Packages Signing Authority) <linux-packages-keymaster@google.com> public key
Fedora (38) <fedora-38-primary@fedoraproject.org> public key
Webmin Developers <developers@webmin.com> public key

**Comment by pfmp-404** [comment]
Hi, 
I have the sames output's and the same problem, unable to update...

**Comment by iliajie** [comment]
The solution for this problem is simple -- manually download latest Webmin 2.100 RPM file and install it using:

```
rpm -U --nogpgcheck webmin-2.100-1.noarch.rpm
```

**Comment by mollcons** [comment]
Because I am using Fedora 38 the rpm command is no longer available. The response I get is:
rpm -U --nogpgcheck webmin-2.100-1.noarch.rpm
rpm: --nogpgcheck: unknown option

If I then use the dnf command instead, the reply is:
dnf -U --nogpgcheck webmin-2.100-1.noarch.rpm
No such command: webmin-2.100-1.noarch.rpm. Please use /usr/bin/dnf --help
It could be a DNF plugin command, try: "dnf install 'dnf-command(webmin-2.100-1.noarch.rpm)'"

**Comment by iliajie** [comment]
```
dnf install rpm
```

**Comment by mollcons** [comment]
That did not work either:

dnf install rpm
Last metadata expiration check: 1:58:30 ago on Thu 03 Aug 2023 21:45:33 BST.
Package rpm-4.18.1-3.fc38.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!

**Comment by iliajie** [comment]
😆 ... then just try:

```
rpm -Uv ./webmin-latest.rpm
```

**Comment by pfmp-404** [comment]
Hi,
unable to install.

**Comment by mollcons** [comment]
Failed with this response:

rpm -Uv ./webmin-latest.rpm
error: open of ./webmin-latest.rpm failed: No such file or directory

**Comment by mollcons** [comment]
There is a further discussion about this on https://forum.virtualmin.com/t/error-gpg-check-failed-unable-to-install-on-fedora-38/120374. Some of the comments seem to point accurately with my experience.

Why therefore has a solution NOT yet been found for this issue? You have had 4 months to resolve it, after all.

**Comment by iliajie** [comment]
> error: open of ./webmin-latest.rpm failed: No such file or directory

What does this error mean exactly if you read it carefully?

**Comment by iliajie** [comment]
> Failed with this response:
> rpm -Uv ./webmin-latest.rpm error: open of ./webmin-latest.rpm failed: No such file or directory

Try the following, it will work:

```
wget https://download.webmin.com/download/newkey/yum/webmin-2.100-1.noarch.rpm
rpm -Uv ./webmin-2.100-1.noarch.rpm
```

**Comment by mollcons** [comment]
[2023-08-04 Webmin Install errors.txt](https://github.com/webmin/webmin/files/12261099/2023-08-04.Webmin.Install.errors.txt)

The download worked, but the install does NOT appear to have worked - full of conflicts and also has the same signature verification FAILURE.

**Comment by jcameron** [comment]
@iliaross what's the underlying issue here? Is it that Fedora 38 doesn't support the old signature format, or that it doesn't support the new one?

**Comment by pfmp-404** [comment]
sudo rpm -Uv ./webmin-2.100-1.noarch.rpm
erro: Verifying a signature using certificate 1719003ACE3E5A41E2DE70DFD97A3AE911F63C51 (Jamie Cameron <jcameron@webmin.com>):
  Key D97A3AE911F63C51 invalid: not signing capable
erro: ./webmin-2.100-1.noarch.rpm: Header V4 DSA/SHA1 Signature, key ID 11f63c51: BAD

**Comment by iliaross** [comment]
> @iliaross what's the underlying issue here? Is it that Fedora 38 doesn't support the old signature format, or that it doesn't support the new one?

The underlying issue is that the new 2.100 package is already signed with the new key and Webmin 2.021 knows nothing about it. Webmin upgrade script should have a parallel repo to use for this purpose.

But anyway, people should stop using Webmin to update Webmin! Everyone should use package manager!



> sudo rpm -Uv ./webmin-2.100-1.noarch.rpm
> erro: Verifying a signature using certificate 1719003ACE3E5A41E2DE70DFD97A3AE911F63C51 (Jamie Cameron [jcameron@webmin.com](mailto:jcameron@webmin.com)):
> Key D97A3AE911F63C51 invalid: not signing capable
> erro: ./webmin-2.100-1.noarch.rpm: Header V4 DSA/SHA1 Signature, key ID 11f63c51: BAD

It works on my Fedora 38. 🤷‍♂️

In particular, if you import the new key and install Webmin repo it just has to work!

Wait, you tried running `dnf clean all` after installation the repo, right? The downloaded package is cashed and update using package manager may still fail, until the packages is redownloaded.

**Comment by pfmp-404** [comment]
Hi,
I solve my problem, is that I still have the Jamie Key present, I eliminate that and perform the commands:
 wget https://download.webmin.com/download/newkey/yum/webmin-2.100-1.noarch.rpm
rpm -Uv ./webmin-2.100-1.noarch.rpm
and problem solved, thanks for the help.

**Comment by jcameron** [comment]
I wonder if we should switch the URL used inside Webmin for downloading the new version directly to the `newkey` path, instead of sourceforge?

**Comment by mollcons** [comment]
I have tried these last suggestions and still get the same response as I provided earlier.

**Comment by iliajie** [comment]
> I wonder if we should switch the URL used inside Webmin for downloading the new version directly to the `newkey` path, instead of sourceforge?

No! We need to provide `upgrade.cgi`  RPM package signed with an old key.



> I have tried these last suggestions and still get the same response as I provided earlier.

If you really want us to help you, you need to provide clear details about what you have tried and which error messages were displayed.

**Comment by mollcons** [comment]
I provided a file showing the responses to the commands recommended.

**Comment by iliajie** [comment]
@mollcons Chris, sorry, I just got back to my computer.

The right command for you to upgrade to Webmin 2.100 using command line is:

```
rpm -Uv --nosignature ./webmin-2.100-1.noarch.rpm
```

A small tip. It would be very easy to verify my initial response and use the right param by running `man rpm | grep -i sign` command.

@jcameron Jamie, I don't think there is a simple solution to this trivial issue, aside from that we always should encourage people to use package manager. There is absolutely no reason not to use package manager for RPM and DEB distributions.

Our problem is, that the signature for Webmin 2.100, when installed using Webmin upgrade script, cannot be _Webmin Developers_ key, and still should be signed with the old _Jamie Cameron_ key. Webmin upgrade script needs to run upgrade at least once for the new key to be imported. Also, it's not clear how Webmin upgrade script would handle upgrades from 2.021 to 2.101. In my perspective, Webmin upgrade script should still install 2.100 first (even if 2.101 is available). As Webmin 2.100 should be still signed with the old key .. and only then install Webmin 2.101 which would be signed using the new key!

Also, I would personally made Webmin upgrade script to try downloading files first from some specific location of `download.webmin.com`, e.g. `https://download.webmin.com/download/manual/rpm/webmin-2.100-1-noarch.rpm` rather than from SF. GitHub and SF RPMs files should be signed with the new key (always). If the key change happens, or whatever scenario that needs specific treatment for only those users who update using Webmin upgrade script, then you could simply drop Webmin 2.100 and 2.101 signed with the old key to `https://download.webmin.com/download/manual/rpm/` and made everyone happy. Users that download RPM files using Github or SF directly and checking a signature or hash sum manually should see the right results. Those files that you could place to `https://download.webmin.com/download/manual/rpm/` would not be exposed to the public, so no one would ever face that problem.

In my perspective, if we still plan to continue to support Webmin upgrade script, we need to implement the support for a separate pool described above, e.g. `https://download.webmin.com/download/manual/rpm/` or similar. I would also suggest to make `upgrade.cgi` to be remotely self-upgradeable. If a new `upgrade.cgi` is available for the download from us, it should be fetched and applied. Upgrade script should re-running itself to make sure that the upgrade would work correctly in the light of new changes. I really don't like how we handle these Webmin upgrades. This is a very smart feature but it won't work correctly in dynamically changing environments.

**Comment by mollcons** [comment]
Thanks. That seems to have worked.

Fedora (and I believe other Red Hat products) now use DNF to perform installs and upgrades of software. See the first Warning para in  https://docs.fedoraproject.org/en-US/fedora/latest/system-administrators-guide/RPM/ for more detail.

**Comment by iliajie** [comment]
> Fedora (and I believe other Red Hat products) now use DNF to perform installs and upgrades of software. See the first Warning para in https://docs.fedoraproject.org/en-US/fedora/latest/system-administrators-guide/RPM/ for more detail.

Yeah, just as much as we don't use `iptables` and use FirewallD, or `dpkg` and use APT.. :--)

`rpm` is the backend for `dnf` ..

**Comment by jcameron** [comment]
> Jamie, I don't think there is a simple solution to this trivial issue, aside from that we always should encourage people to use package manager. 

Maybe the right fix is for the upgrade UI in the Webmin Configuration module to offer an option to install from the configured repository, and use that by default when upgrading from the dashboard?

**Comment by mollcons** [comment]
> > Jamie, I don't think there is a simple solution to this trivial issue, aside from that we always should encourage people to use package manager.
> 
> Maybe the right fix is for the upgrade UI in the Webmin Configuration module to offer an option to install from the configured repository, and use that by default when upgrading from the dashboard?

That sounds a good recommendation.

**Comment by iliajie** [comment]
> Maybe the right fix is for the upgrade UI in the Webmin Configuration module to offer an option to install from the configured repository, and use that by default when upgrading from the dashboard?

As we already provide upgrades using UI the way we do, I think the right solution would be is to make it more resilient (by making it more flexible) in ways I suggested in my previous comment ..

**Comment by jcameron** [comment]
A mostly working fix to use the repository is here : https://github.com/webmin/webmin/commit/1fb3bfa6ef92a4fc231ec203a5e2fb7e75ec9c58
