### ISSUE TITLE
NPM and forwarding client IP

### ISSUE THREAD

**Issue by tokar86a** [webmin/webmin#2068]
Hello

i am trying to figure out how i can send the client ip to my webmin/virtualmin server.

NPM logs show the following infomration: [31/Dec/2023:23:15:38 +0000] - 200 200 - GET https tokar86a.top "/tag/icedtallchai/" [Client 66.249.66.82] [Length 10150] [Gzip -] [Sent-to 192.168.1.146] "Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.6099.71 Mobile Safari/537.36 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)" "-"

But when i check the logs on Apache access logs in Virtualmin/webmin: 192.168.1.118 - - [01/Jan/2024:15:53:29 +0100] "GET / HTTP/1.1" 200 17140 "-" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Mobile Safari/537.36"

192.168.1.118 is my docker host that is running the NPM. How can i get it to show the real visitor ip instead of the internal ip?

**Comment by iliajie** [comment]
Hello,
> How can i get it to show the real visitor ip instead of the internal ip?

**Comment by iliajie** [comment]
Hello,

Happy New Year!

> How can i get it to show the real visitor ip instead of the internal ip?

I don't think this problem is related to Webmin in any way.

---

Although, the solution is probably lies in forwarding the real IP address. If your NPM config already does it, e.g. using:

```
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
```

.. then you need to tell Apache to trust the `X-Forwarded-For` header from your NPM. `X-Forwarded-For` is part of Apache `mod_remoteip` module.
