### ISSUE TITLE
web terminal not working behind ha reverse proxy

### ISSUE THREAD

**Issue by kindlydodo** [webmin/webmin#2144]
webmin version: 2.111

i click on the left bar > Terminal icon, the popup is opening, and it displays "CONNECTING..." but i never get to the terminal.

This are the Browser (Chromium) logs:

```
Mixed Content: The page at 'https://webmin.site.com/sysinfo.cgi?xnavigation=1' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://webmin.site.com/xterm/ws-563'. This request has been blocked; this endpoint must be available over WSS.
```

```
Uncaught DOMException: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
    at https://webmin.site.com/unauthenticated/js/bundle.min.js?2110001019999999999:178:81906
```

tmp log file:
```
Running shell '/bin/bash -bash' with pid 8940
listening on port 564
timeout waiting for connection at /usr/share/webmin/xterm/shellserver.pl line 103.
```

**Comment by iliajie** [comment]
Hello,

The default socket protocol in Webmin is `wss`. If you ran Webmin without SSL (which is not recommended, and what you don't do), then you should have changed the **Hostname for WebSocket connections** option to `ws://your-host:10000` on the **Terminal → Configuration** page. The same true visa versa or in case of using revers proxy.

Simply saying make connection to Webmin using `https` and use `wss` for socket connection, or configure it otherwise in module config.

Nevertheless, you should always avoid mixed content, and ensure that your HA Proxy is configured to proxy connections to `wss` instead.

**Comment by kindlydodo** [comment]
Thank you!

As far as i change to manual and set the value : `wss://webmin.site.com` it works

**Comment by shoulders** [comment]
@kindlydodo if all is working, can you close the issue 😄

**Comment by karwrkinga1** [comment]
Where do I go to update this WS://webmin.site.com?

**Comment by harifhaqim** [comment]
Hi, I'm also having the same issue with Cloudflare Tunnel...I can't find "Hostname for WebSocket connections" in Terminal Configuration...how could I solve it?

**Comment by iliajie** [comment]
> Hi, I'm also having the same issue with Cloudflare Tunnel...I can't find "Hostname for WebSocket connections" in Terminal Configuration...how could I solve it?

Thanks for the heads up! It was moved to "Webmin ⇾ Webmin Configuration: Ports and Addresses" page.

**Comment by iliaross** [comment]
For anyone having issues with Cloudflare Tunnel and Webmin, check out this post that explains what needs to be done:

https://forum.virtualmin.com/t/webmin-2fa-cloudflare-tunnel-ii-after-the-new-update-2-402/133989/5?u=ilia
