### ISSUE TITLE
I can't change the stats history period

### ISSUE THREAD

**Issue by AndreBrusoft** [webmin/webmin#2230]
I'm not finding where to change the stats history display period in version 2.201.
Where can I change from 10 minutes to 24 hours?

![image](https://github.com/user-attachments/assets/9664590d-c275-4ec9-a7dd-023fdb3acda9)

**Comment by iliajie** [comment]
> Where can I change from 10 minutes to 24 hours?

This is no longer an option. Storing stats for 24 hours is very inefficient and results in a huge file, around 5 MB.

The maximum duration now is 3600 seconds (1 hour). The default is 1200 seconds (20 minutes).

You can manually change it to 3600 seconds by running the following in the browser's console:

```javascript
settings_sysinfo_real_time_stored_duration = 3600;
theme.config.save();
```

Currently, it's not possible to set it for more than 1 hour (3600 seconds) due to a sanity check. Though I could technically make it possible, but it won't be available as an option.

**Comment by rmatzinger** [comment]
I'm having trouble with this.  With Authentic Theme 21.20.5  I get different results on different servers.   Setting to 1200 seconds results in different displays:

Server 1:   7:00:00 PM 12:31:29 AM 6:02:58 AM 11:34:27 AM 5:05:57 PM 10:37:26 PM 4:08:55 AM 9:40:24 AM 3:11:54 PM 8:43:23 PM 2:14:52 AM 7:46:21 AM   And no graph data is shown, no data shown in any of the graphs.   stats.pl is not listed in running processes. 

Server 2:  1:05:07 PM 1:06:47 PM 1:08:28 PM 1:10:08 PM 1:11:49 PM 1:13:29 PM 1:15:10 PM 1:16:51 PM 1: 18:31 PM 1:20:12 PM 1:21:52 PM 1:23:33 PM  Data is shown in all graphs.  But stats.pl is using over half my installed memory: 
     1.04 GiB  /usr/local/bin/perl /usr/libexec/webmin/authentic-theme/stats.pl 555

Server 3:  Normal times listed (same as server 2) and data shown in graphs but stats.pl is only using a fraction of that memory on a server with the same 2GB installed memory:
     40.53 MiB  /usr/bin/perl /usr/libexec/webmin/authentic-theme/stats.pl 555

Collect system status in background is set to 5 minutes on each one. All have Enable real-time monitoring = Yes.

I thought that perhaps reinstalling Webmin would help but that option is no longer available in Webmin Configuration. 

What can I do to resolve these issues?

**Comment by iliajie** [comment]
> And no graph data is shown, no data shown in any of the graphs. stats.pl is not listed in running processes.

Try manually restarting Webmin and force-reloading browser's page.

> and data shown in graphs but stats.pl is only using a fraction of that memory on a server with the same 2GB installed memory:
> 40.53 MiB /usr/bin/perl /usr/libexec/webmin/authentic-theme/stats.pl 555

This looks fine!

> Data is shown in all graphs. But stats.pl is using over half my installed memory:
> 1.04 GiB /usr/local/bin/perl /usr/libexec/webmin/authentic-theme/stats.pl 555

That’s not right. Try clicking the "Force System Information Refresh" button in the top right of the dashboard to clear all related cache data.

> All have Enable real-time monitoring = Yes.

That's right!

> I thought that perhaps reinstalling Webmin would help but that option is no longer available in Webmin Configuration.

You shouldn’t reinstall Webmin; I doubt it will help. At most, you should consider rebooting your server.

**Comment by rmatzinger** [comment]
On my server #2 with the memory use issue, I have restarted webmin and forced a page reload (with nocache) but no difference in memory usage.  Force System Information Refresh didn't result in any memory use change. 

I always keep my servers up-to-date regarding packages but I just noticed that somehow my servers #1 and #2 are not using the same Theme version as the Server #3.  The server #2 (memory problem) is running Webmin 2.201 and Authentic Theme 21.20.5.   Server #3 (no memory problem) is running Webmin 2.202 and Authentic Theme 21.20.7.    I can't find any way in Webmin to update.  Yum update doesn't find any packages to update and Webmin doesn't show any Theme update option.   I could install the newer theme but that might not work correctly with a slightly older Webmin.    

Another possible complication is that servers #1 and #2 OS are Centos-7 and #3 is Rocky 9.  That probably explains why no updates are available.  Can I force an update to the latest Webmin and Theme by downloading and installing webmin-2.202-1.noarch.rpm ?

**Comment by iliajie** [comment]
> I could install the newer theme but that might not work correctly with a slightly older Webmin.

You should fix the repos and install the latest RPM package using a package manager, or do it manually if that doesn't work.

**Comment by rmatzinger** [comment]
CentOS Linux 7.9.2009 EOL reached
Centos-7 is EOL so I don't know how to fix the repositories.  

I'll just try installing the latest RPM.

Thanks.

**Comment by rmatzinger** [comment]
I manually updated Webmin on both server #1 and #2 using the latest .RPM file: webmin-2.202-1.noarch.rpm.  So far so good, the Stats History display issues are resolved on both.   The memory issue on #2 is significantly smaller: 
   36.59 MiB  /usr/bin/perl /usr/libexec/webmin/authentic-theme/stats.pl 556
however, before it seemed to just grow and grow so I'll watch that.  

I guess those servers won't receive update announcements so I'll do it manually until I can update them all to a new OS.  Unfortunately that will require a lot of work because it will require significant configuration adjustments and break my application code.  

Thanks again.
