### ISSUE TITLE
Update halts after Apache update, when started via Apache proxy

### ISSUE THREAD

**Issue by j0bb13** [webmin/webmin#296]
I've configured an Apache domain to be a proxy for port 10000 of my server. I host a couple websites for some friends and I tried to keep it as simple as possible for them. Since https://server.domain.tld shows the content of https://server.domain.tld:10000, this relies on Apache and Webmin.

I usually go to Webmin via https://server.domain.tld:10000, so this isn't a problem. But when I accidentally go to :80 and run a package update that concerns Apache the update will stop after the Apache update, because Apache was restarted and I'm using Apache to view Webmin. 

Today I noticed this with the package _libapache2-mod-svn_. My server installed 21 updates, but didn't continue after libapache2-mod-svn. The 30 other updates I could start by starting the package updates again. Since there was no other update that required a restart of Apache all 51 were installed afterwards.

My feature request:
Is it possible to show a warning when Webmin detects the local Apache installation will be restarted during the updates and Webmin is viewed via a local Apache proxy?

**Comment by jcameron** [comment]
The connection being broken isn't too surprising, as you're restarting the Apache that the connection is being proxied via. Displaying a warning for this isn't really practical, because Webmin has no way of knowing which packages contain or might restart Apache - naming isn't consistent across operating systems.

However, what I will do is ensure that the update continues to run in the background in this case.

**Comment by j0bb13** [comment]
:+1:
That's plenty, thank you. It solves the possible situation where someone might not understand why the updates didn't finish.
