### ISSUE TITLE
NGINX SSL adds unwanted "default ssl" directive to config - No template for NGINX config

### ISSUE THREAD

**Issue by bilekt3** [webmin/webmin#444]
Hello I have following issues with NGINX module

Nginx module does not allow you to create custom configuration with placeholders. Or it is hard to find it in system.

Nginx SSL always add "IP default ssl;" configuration option which is unwanted if you have more than one SSL nginx site in system available.

**Comment by jcameron** [comment]
Doesn't that just define which server will be the default for HTTPS connections that don't specify a hostname?

**Comment by bilekt3** [comment]
Probably but it is unwanted behavior if you have more than one SSL server in your system (in case Lets Encrypt every :D)

**Comment by jcameron** [comment]
Ok, but what problem does this cause? Does Nginx refuse to load a config if there is more than one default?

**Comment by jcameron** [comment]
Looking at the code, Virtualmin should only add this for the first SSL server.

**Comment by bilekt3** [comment]
I do not want any default SSL server, I would like to prefer to not have any default configured by default. 

Direct cause is that SSL on server is messed up and I have to remove default by hand and restart server. Which is very inconvenient.

As stated at first post this all might be configured through some sort of "template". For example, I would like to prefer use directives as "listen 80; listen 443 ssl;" also there is some very anoing configuration when you would like to enforce SSL by default and creating two basic server directives (one listen 80 and 443 as custom directives).

**Comment by jcameron** [comment]
So, if no server has `default ssl` and Nginx receives an SSL connection that doesn't match any host, which server's contents will be returned?

It Apache, it's always the first one.

**Comment by DavidBruchmann** [comment]
As far as I experienced with one main-domain and sub-domains as well as sub-sub-domains the main-domain is returned but that might depend on the configuration too even I never configured something like "default" or "default fallback". Also it's possible that the web-space-root is returned instead of the main-domain.
At least it's not the first configured domain like in Apache.
In general the assumption that SSL is activated either completely or not at all might be wrong too in some environments. Like this you're forced in a tough migration-process perhaps and it's still questionable if really all domains shall run on SSL even if customers never pay for the migration-service.

**Comment by bilekt3** [comment]
I have made "workaround" to prevent default server with creation of "default" website for server with blank page. Default is not problem anymore. But it is not ideal solution. 

Nginx template is still valid request I am going to create separate issue for it.
