### ISSUE TITLE
Unable to login at Virtualmin.com

### ISSUE THREAD

**Issue by singhdd93** [webmin/webmin#500]
Hi, I know this doesnt belong here. But I didnt have any other way to contact you guys.
I am unable to login at Virtualmin.com

Whenever I try I get 
```
The username singhdd has not been activated or is blocked.
```

My account is 1Year and 7-8 months old. I also have 1 virtualmin license running from that account.

Username: singhdd

Email: <removed>

**Comment by qooob** [comment]
Hi, 

We're taking a look at your issue. 

Please be patient. Sorry for the inconvenience


---

You better edit your message and remove the email address.

**Comment by qooob** [comment]
Hi, :smiley: 

We apologize for the delay.

Your account has been re-activated. You can login now.

It's been deactivated as spam system false positive reaction.

Have a good day,
Ilia

**Comment by singhdd93** [comment]
Thanks for fixing this.
I never post much until I have some issue. I dont understand which posts did the system consider spam.

**Comment by swelljoe** [comment]
Apologies! It wasn't your posts that triggered the spam filters, it was the IP address you were coming from, I believe. We've had a tremendous amount of spam over the past few months, and so I made use of "StopForumSpam.com" to filter out spam accounts, but it caught a few innocent bystanders because they came from IP addresses that had sent spam at some point. I  have since adjusted the parameters to be more forgiving, and may disable it entirely, as it has had quite a few false positives. IP-based filters are notoriously problematic.

It was nothing you did wrong. Just our system being kinda dumb about spam.

**Comment by singhdd93** [comment]
Oh I get it. Our ISP provide dynamic IPs, so these are kinda misused by spammers. We guys are kinda completely blocked from some forums just because our IPs are in their block list.

I completely understand. Spamming is great problem and strict actions should be taken against it. I would suggest that you dont remove those spam filters.

Just leave a message somewhere that If people get blocked than they can contact you at `your prefered contact way` to get themselves unblocked. Only the genuine person will try it, none of the spammer has time for this
