### ISSUE TITLE
Diskspace error causes the server to "freeze".

### ISSUE THREAD

**Issue by tdiddi** [webmin/webmin#665]
Hello,

For some reason Webmin 1.850 thinks my diskspace is full und neither apache or mysql servers are working.
I attached some screenshots.
![bug2](https://user-images.githubusercontent.com/1759475/31864036-2f370394-b757-11e7-9ba0-f850708ebd2f.png)
![bug1](https://user-images.githubusercontent.com/1759475/31864037-2f586124-b757-11e7-9f79-3bf58ed8cd63.png)
![bug3](https://user-images.githubusercontent.com/1759475/31864038-2f73c784-b757-11e7-9aae-fa099e3a03a8.png)

I cant upgrade Webmin as well over the web interface.

I would be glad about help with my problem.

update1:

> df -h

 output:

```
Filesystem      Size  Used Avail Use% Mounted on
/dev/simfs       98G  6.5G  178M  98% /
devtmpfs        768M     0  768M   0% /dev
tmpfs           768M     0  768M   0% /dev/shm
tmpfs           768M   88K  768M   1% /run
tmpfs           768M     0  768M   0% /sys/fs/cgroup
tmpfs           154M     0  154M   0% /run/user/0

```

update2:
I just found, it may be a problem with my provider. Iwill keep this updated.

**Comment by swelljoe** [comment]
This isn't a Webmin issue. You're almost out of disk space. You need to fix that by deleting some files. Nothing that requires writing to disk will work with a full disk (there's usually a small amount of disk space reserved for root, but any other user, including system users, will not be able to write to disk until you free up space).

Check your logs in /var/log. You may find something has been generating a lot of logs without rotating regularly enough (or because of a problem).

**Comment by chris001** [comment]
It'd nice to have a "disk cleanup" function, where Webmin could tell the admin user, "Disk space is low, package updates cannot complete, would you like webmin to cleanup disk space for you, here are the most usual common files or folders to delete."

**Comment by swelljoe** [comment]
That'd be a good first module project. Hint, hint. ;-)

**Comment by tdiddi** [comment]
I was running webmin on a VPS and it was a problem with my Provider. There was no more diskspace free on the root machine.
They fixed it now and everything is working again.
