### ISSUE TITLE
foreign_available() blocks some modules on syno-linux

### ISSUE THREAD

**Issue by gnadelwarty** [webmin/webmin#745]
I wanted to add the ipkg packgae manager to module software, but its not listed.
when I navigate to `/software/index.cgi` or `config.cgi?software` I got the message:

> module is not installed on your system

I check ACLs module access, etc but the module is also there not listed. I tracked it down to `foreign_available()` which denies access to module, but don't understand why :-(

for now I dieabled the `foreign_available` checks on my development synology so I can navigate to module and config "by hand" and start developing.

just for couriosity I checked with authetic-theme and gray-framed theme.
Where is the hidden magic to prevent software module is not accessible and not displayed?

**Comment by jcameron** [comment]
This is most likely caused by the Software Packages module not being compatible with Synology, if you've defined it as a whole new OS type in Webmin (which I guess is the case based on https://github.com/webmin/webmin/pull/737)

Fixing this is complex - does Synology have it's own custom package manager that is unlike YUM or APT?

**Comment by gnadelwartz** [comment]
it has its own package management system plus a community system named ipkg.
currently I defined it as general-linux, no more as syno-linux.

I already guessed the os definition may the reason for this, but cant find where its wired.
 compatibilty of module software should be in a more visible place and  not defined by some deeply wired rules in webmin. an easy way may be an extra field in os_list.txt with the default package manager

I can understand using the software module can be dangerous, but hide it without an option to make it accessible for root  is 🤔

**Comment by jcameron** [comment]
The thing about the `software` module is that it loads in code specific to the OS type, so it can't be opened up to all systems. What you probably want to do is bring back the `syno-linux` type, and in the `software` directory create a `config-syno-linux` file with `package_system=` set to a new package system type. You can see how this works here : https://github.com/webmin/webmin/blob/master/software/software-lib.pl#L11

**Comment by gnadelwartz** [comment]
after I brought back syno-linux I have a similar issue with module mount.

when generic-linux was used mount can be opened and disc usage was shown in system information.
after switching to syno-linux the module is no more displayed and no disc usage is shown.

I can not find the reason why, similar to the software module access is blocked by `foreign_availible()` and friends but don't know why ...

**Comment by gnadelwartz** [comment]
hm,it seems I miss something fundamental

many system modules refuses to open with this message:
![image](https://user-images.githubusercontent.com/4593242/34486083-45acaaca-efce-11e7-8a28-f0acde5160e6.png)

the following modules work with the same settings, but generic-linux instead of sysno-linux:
![image](https://user-images.githubusercontent.com/4593242/34486049-1fb75db0-efce-11e7-9e33-433a4a1419a8.png)

**Comment by gnadelwartz** [comment]
@jcameron  I think I got the root cause.

in the affected module.info files every linux version is listet sepeartly:
```
os_support=solaris slackware-linux redhat-linux mandrake-linux debian-linux suse-linux united-linux hpux freebsd osf1 irix unixware openserver macos open-linux turbo-linux openbsd corel-linux cobalt-linux aix netbsd msc-linux generic-linux gentoo-linux trustix-linux sol-linux coherent-linux openmamba-linux windows pardus-linux
```
may by we should change this to *-linux wehn many linuxes and generic-linux is listed:

`os_support=*-linux solaris hpux freebsd osf1 irix unixware openserver macos openbsd aix netbsd windows`

I'll provide a patch

**Comment by jcameron** [comment]
That's generally safe, as long as the module really can support all Linux variants. For example, in the case of the mount module, there needs to be a config- file for each possible Linux type.

**Comment by gnadelwartz** [comment]
my general idea is if generic-linux is supprted the module can supprt any linux variant, the question is how to provide a config file for every linux variant? 

may be its possible to  have a `config-ALL-linux` to provide default config for linux variants without own config file, but I guess this is currently not implemented.

**Comment by jcameron** [comment]
You can't really have a generic config that works with any Linux in most cases, because every distribution has its own config file locations. Hence each distro has to be individually whitelisted.

**Comment by gnadelwartz** [comment]
OK, l understand and will check module by module if all config files are availible. if not l'll add only syno- linux.

is it save to assume that all possible linux variants has a config file in he webmin root dir?

**Comment by gnadelwarty** [comment]
fixed by PR https://github.com/webmin/webmin/pull/760
