### ISSUE TITLE
Suppress new package notification while update is in progress

### ISSUE THREAD

**Issue by mvglasow** [webmin/webmin#863]
To reproduce:

* Set up a system, install Webmin, wait for a large number of package updates to become available.
* Log in to Webmin; you will get a notification about new packages (54 in my case).
* Install the packages via Webmin.

Actual behavior:

* When the system is in the middle of installing updates, I get a new notification about packages being available (23 in this case).

Expected behavior:

* No new notifications about packages while an update is in progress. When I’m installing packages after receiving such a notification, it’s kinda obvious that I have somewhere between 0 and the last reported number of updates that are not yet installed—no need to tell me until the update is through.

**Comment by jcameron** [comment]
Good idea .. I'll look into adding this

**Comment by gnadelwartz** [comment]
i had this also in my test unstallation on ubuntu. since l run the vm last 2 month ago, ubuntu immediately started to pull updates and wemin nags me also about 169 missing updates.

even webmin don't know that ubuntu already started pulling updates and warning can be disabled, it would a nice feature if webmin can detect that uodate command is running.

since update command should be provided from e.g. yum-update-lib.pl it may possibleto check if it's already running from outside webmin

**Comment by qooob** [comment]
Fixed on the theme side.

**Comment by jcameron** [comment]
I've also started work on a feature to implement this in webmin core.

**Comment by jcameron** [comment]
The next webmin release will not prompt you to update packages that are already being updated.
