### ISSUE TITLE
Menu language in English

### ISSUE THREAD

**Issue by TMTYD** [webmin/webmin#877]
Hi

the menu language is in English, although I have set everything in German in the settings, see screenshot.

How can I set the menu language in German?

What I noticed, it sounds better Manual, instead of like hand, see screenshot.

Menu language in English
![menuesprache](https://user-images.githubusercontent.com/29516076/37640557-80dc3064-2c16-11e8-96c9-63ac1ba37c47.png)

My marked in red
![handisch](https://user-images.githubusercontent.com/29516076/37640558-8364a80c-2c16-11e8-8e22-4b0436fe55db.png)

My marked in red
![handisch1](https://user-images.githubusercontent.com/29516076/37640560-84afb634-2c16-11e8-886e-3d3bfc3d47b4.jpg)

**Comment by gnadelwartz** [comment]
Should be fixed in 1.881 or next release ...

Das das Menü in english angezeigt wird sollte mit 1.881 behoben sein, spätestens aber mit dem nächsten Release.

Bei dem "Händisch" habe ich auch mit mir gerungen ob es nicht besser "Manuell" sein sollte ...

Workaround für das Menü in deutsch ist die automatische Spracherkennung einschalten:
![bildschirmfoto vom 2018-03-20 10-49-36](https://user-images.githubusercontent.com/4593242/37647452-93f77990-2c2c-11e8-94f5-8f05474bc71d.png)

**Comment by TMTYD** [comment]
ok danke @gnadelwartz 

ich finde auch das es besser Manuell heißen sollte als wie Händisch

**Comment by TMTYD** [comment]
@gnadelwartz 

jetzt habe ich aber wieder dieses Problem  #836

**Comment by gnadelwartz** [comment]
im Augenblick musst du zwischen den beiden Varianten wählen bis die nächste Version draussen ist, sorry

**Comment by TMTYD** [comment]
ok dann warte ich einfach die nächste version ab danke
