### ISSUE TITLE
[Feature Request] Interactive Shell

### ISSUE THREAD

**Issue by michacassola** [webmin/webmin#926]
Hi,

I would love the shell to be interactive to be able to fully replace logging in remotely.
The so called "Text Login" seems tobe interactive but the PASTE button is broken (however it is supposed to work). Please merge the two tools to something powerful (interactive shell with easy ctrl + v pasting).

Thanks!

**Comment by swelljoe** [comment]
There's a discussion about this over on the Authentic Theme (Ilia is the developer of the popup shell that I think you're talking about). That issue is here: https://github.com/authentic-theme/authentic-theme/issues/1037

We're planning to merge in an interactive shell at some point, but there are still some technical issues that need to be resolved.  But, that's probably the place to discuss the terminal, since there's already a lot of talk there (realistically, it'll require at least attention from at least a couple of us, just because it involves heavy lifting on both the back end and front end).

**Comment by rostovtsev** [comment]
I will start looking at it in the beginning of fall, right after I finish new mail UI.

There are unclear (for now) back-end parts, like session authentication and some other but it's doable, I believe. We'll work it out eventually.

Please be kind continuing discussion on:
https://github.com/authentic-theme/authentic-theme/issues/1037
