### ISSUE TITLE
Cluster Users and Groups: Add invalid character to user and groups upon save

### ISSUE THREAD

**Issue by deddymarzuki** [webmin/webmin#945]
I have this weird issue, that when I use cluster users and groups to edit user, it will add an invalid character '@' to /etc/passwd and /etc/group. Any idea?

Setting upon save
![image](https://user-images.githubusercontent.com/7510716/42996516-5e8b5f9a-8c46-11e8-99fc-fcc395abe9ab.png)

**Comment by jcameron** [comment]
Can you post an example of one of the invalid lines being added to /etc/passwd ?

**Comment by alexkararo** [comment]
Hello. I just encountered this issue to, running Webmin version 1.920. 
I edited one user from "Cluster Users and Groups", and it cmpletely broke /etc/passwd and /etc/groups file, by adding "^@" (this is the character it shows in nano). 

I had to enter rescue mode on the server to fix the issue, manually corecting the files. 

Any ideas on how I can use cluster users and groups? This seems like a big issue. :(

**Comment by jcameron** [comment]
Interesting, looks like you added a null byte - I will add a check in the next release to prevent that.

**Comment by alexkararo** [comment]
Hello jcameron. 

Actually I can reproduce the steps:
1. Went to webmin cluster users and groups
2. Search for my username (akara) with find. 
3. Changed the default primary group, then pressed save. 
4. After the save, my /etc/passwd and /etc/groups where corrupted, by replacing the akara username with akara^@akara in all files, but only on the master server. The other servers added in cluster list where left untouched.  

So I did not add a null byte by myself, somehow webmin introduced it. I was unable to login afterwards on the server, I had to manually correct all files. :( 

Searching the web, I found this similar issue: https://sourceforge.net/p/webadmin/bugs/5168/

In the meantime, I will try to install the old virtual server theme, see if I can use the user cluster functionality like this. 

Thank you!

**Comment by rostovtsev** [comment]
@alexkararo Please try this patch:

https://github.com/webmin/webmin/commit/0da2af51c6fecadb191256021e22c14e455c49d7#diff-386f498865bcbec736fad4fb80306abaR723

After applying it, restart Webmin and try again.

**Comment by jcameron** [comment]
@iliaross could this be a theme issue with the old HTML forms in use in the Cluster Users and Groups module?

**Comment by alexkararo** [comment]
Hello, 

I just installed webmin-virtual-server-theme_9.3_all.deb pachage and reverted to the old theme. 
Now all functionality is working, so I think it is theme related. 

Kind regards

**Comment by rostovtsev** [comment]
@jcameron I have done more investigation on this.

It's not going to work stable under any circumstances, in single-page application themes, if rendered HTML is _that_ broken.

**Explanations why it's not working and what is broken**

The problem is, when placing form tag element inside of the table or table row tag element, the returned HTML output happens to be broken. The rendered HTML looks like this:

```HTML
<table>
....
<form>
<input type="hidden" name="olduser" value="gamer">
<input type="hidden" name="host" value="0">
<input name="user" size="10" value="gamer">
....
<tbody><tr> <td><input type="submit" value="Save"></td>
<form action="delete_user.cgi"></form>
<input type="hidden" name="user" value="gamer">
....
</form>
```

As you can see, the whole thing rendered unexpectedly wrong, making _save form_ contain _delete form_, which leads to the form data submitted to the server with `name="gamer"` as an _array_, because now we have two name params sent.

**Example**

![image](https://user-images.githubusercontent.com/4426533/62486826-e7189180-b7c8-11e9-8439-f7be793f94e0.png)

**Solution**

For example, if we simply deleted from `cluster-useradmin/edit_user.cgi` file the last form for deleting user _or_ changed the param name `user` to, let's say, `del_user` _or_ changed the logic in parsing user param, making sure, when user param passed as an array, it wouldn't be flattened to the string (this is where we get this null `\00` char introduced) making the whole thing being saved in broken way.


---


After all, I have one misunderstanding! Jamie, what makes `cluster-useradmin/save_user.cgi` being progressive? It doesn't have `ui_print_unbuffered_header` subs used anywhere, and I am not sure how the theme could reliably detect it. I can add it manually but I need to know, the old school patterns, that makes it progressive.

**Comment by rostovtsev** [comment]
Okay, I have [made a patch](https://github.com/webmin/webmin/commit/55cfbd140cb89cf07777553f148164954d2effca) to address this issue. Next Webmin release will have this fix.

Thank you for reporting.

Please, feel free to submit any other bugs found.
