### ISSUE TITLE
Receiving perl execution failed - Your password has expired (at /usr/share/webmin/password_change.cgi line 12)

### ISSUE THREAD

**Issue by luizfschrickte** [webmin/webmin#947]
Hi, 

After a webmin update to 1.890 I can't use the `chage 0` command on linux to force a user to change its password anymore because when logging on webmin it receives the message:

Perl execution failed - Your password has expired [...] at /usr/share/webmin/password_change.cgi

Looking at the file, apparently webmin is denying the expired password... because the password is expired!

The most weird part is that the password_change.cgi file in the 1.890 tgz file is different from the file in the git 1.890 tag! And exactly line 12 has changed... From the GIT repository info, this file was theoretically changed last time only in 2014!

The problematic line 12 is:
`$in{'expired'} eq '' || die $text{'password_expired'},qx/$in{'expired'}/;
`

Which was, in 1.860 version AND currently is on the github master and 1.890 tag sources:
`$miniserv{'passwd_mode'} == 2 || die "Password changing is not enabled!";
`

So, may I correct this manually or am I doing something wrong? Why is this code in the deb file and not in the GIT sources.. am I looking in the wrong place?

Thank you very much!
Luiz Fernando

**Comment by jcameron** [comment]
You're right, there was a local edit to that file on my packaging system which was incorrect. Putting back the contents from the repo should fix the problem.

**Comment by SaulGoodman1337** [comment]
> You're right, there was a local edit to that file on my packaging system which was incorrect. Putting back the contents from the repo should fix the problem.

Good job @jcameron ... really good job... I am thrilled

**Comment by rostovtsev** [comment]
@SaulGoodman1337 It wasn't intentional in any way! We over looked it. This file was maliciously modified. We don't create back-doors in our software on purpose! Besides, it's unclear why _this kind of exploit_, so _obvious_, _open_, and affecting so little installs, as only very few systems have password reset on, because by default, we have this feature _set to off_.

**Comment by SaulGoodman1337** [comment]
I am well aware that you are not deliberately spreading malicious code. However, I am absolutely surprised with how much operational blindness you overlooked this bug report.

Please do your homework better in the future. In this case, this is simply not acceptable for a software that intervenes as deeply in the system as Webmin does.

**Comment by wiserweb** [comment]
Hi @SaulGoodman1337 you need to relax. It's your assumption that it was operational blindness. It's also not necessary to make the whole world aware of your victimhood mentalitybut you seem to have no issue with it.

If you ever get close to creating something the magnitude of Virtualmin or Webmin then, only, maybe, then, your opinion might be taken seriously.

As a long time customer and contributor to both Webmin and Virtualmin I KNOW 100% that the team top notch.

Good luck with life.

**Comment by SaulGoodman1337** [comment]
Ahhh beautiful.
The people who have to become directly personal out of nothing. They are my favorite :)

**Comment by Neustradamus** [comment]
@jcameron, @iliaross, @swelljoe, @webmin, @usermin, @virtualmin: Time to take little minutes for have a perfect github for Virtualmin products?
- https://github.com/webmin/webmin/issues/876

**Comment by art-lucas** [comment]
FYI, I've just upgraded to 1.930 this morning after receiving the report from [SecurityWeek](https://www.securityweek.com/webmin-backdoored-over-year) that stated:

`To exploit the malicious code, your Webmin installation must have Webmin -> Webmin Configuration -> Authentication -> Password expiry policy set to Prompt users with expired passwords to enter a new one. This option is not set by default, but if it is set, it allows remote code execution`

Right after reading this, I checked my config and saw that `Webmin -> Webmin Configuration -> Authentication -> Password` **was** set to `Password expiry policy set to Prompt users with expired passwords to enter a new one`. This **was** by default, since I **never** changed that value.

Now, the $1m question is: how do I know my system has never been tempered with through this backdoor? Is there a way to verify/trace that? Needless to say that this is **very worrying** as per this [report](https://www.pentest.com.tr/exploits/DEFCON-Webmin-1920-Unauthenticated-Remote-Command-Execution.html) a root shell can/could have been been used very easily.

**Comment by jcameron** [comment]
Looking back, I made a big mistake in ignoring this ticket - at the time I assumed it was just a stupid copy/paste error I made in password_change.cgi and never checked it. Only much later was it pointed out that the `qx` operator in Perl actually executes code :-(

**Comment by c4td0g8** [comment]
But now why u offical website still direct download page  to sourceforge.net?

http://www.webmin.com/download.html  >> https://sourceforge.net/projects/webadmin/files/ (which contain  executes code backdoor )

**Comment by art-lucas** [comment]
Where should the latest version be downloaded from, from [GitHub](https://github.com/webmin/webmin)?

**Comment by jcameron** [comment]
Version 1.930 on sourceforge and linked from http://www.webmin.com/download.html is safe.

I am intentionally keeping older versions around in case anyone wants to analyze them.

**Comment by swelljoe** [comment]
It's worth noting that no release on github has ever been exploitable via this mechanism, including the versions that were exploitable from SourceForge, since the code on github never had these bugs. But, for running it i production, you'd want to use yum or apt, so it's easy to update.

**Comment by luizfschrickte** [comment]
Sad that I didn't realize the potential problem of this issue before :'( 

Is the build infrastructure safe or is it safer to keep using GitHub versions from now on?

Thank you

**Comment by swelljoe** [comment]
I always recommend running the version from apt or yum repositories.

This issue aside, running a current version is the most important thing to do with regard to security (for any software, not just Webmin). We'll work on reproducible and verifiable builds for the future, and the 1930 release was built from a fresh git checkout on new infrastructure (and hand-checked for this issue). That was a rushed affair, since we didn't have any early disclosure of the issue before it was in the wild, but we'll spend more time on the problem for the next release.

**Comment by Pwned55** [comment]
hmmmm
