### ISSUE TITLE
Iptables rules saving error when using conntrack

### ISSUE THREAD

**Issue by MrKich** [webmin/webmin#948]
After upgrading to webmin 1.890 I ran into rules saving problems.

OS: Ubuntu 18.04.1 LTS
Kernel: 4.15.0-23-generic

For example, one my rule from /etc/webmin/firewall/iptables.save :

`-A INPUT -p tcp -m tcp -m multiport -m conntrack -j ACCEPT --dports 33844,22089,33853,22108,33856  --ctstate NEW`

After clicking save button webmin shows error:

`WARNING! Your current IPtables configuration is invalid : iptables-restore v1.6.1: unknown option "--ctstate" Error occurred at line: 10`

And rule now changed to (-m conntrack dissapears):

`-A INPUT -p tcp -m tcp -m multiport -j ACCEPT --dports 33844,22089,33853,22108,33856 --ctstate NEW`

In webmin rule edit page:

"Additional parameters" sets to  `--ctstate NEW`
"Additional IPtables modules" is empty even after I added "conntrack" and saved it (after that it does not show error, but I have to insert conntrack to modules each time I want to edit a rule)

If instead of using "additional parameters" I set "Connection states" to equals and select any type of states then following error appears:

`WARNING! Your current IPtables configuration is invalid : iptables-restore v1.6.1: conntrack: At least one option is required Error occurred at line: 10`

And rule now changed to (-m conntrack added but without --ctstate's):

`-A INPUT -p tcp -m tcp -m conntrack -m multiport -j ACCEPT --dports 33844,22089,33853,22108,33856`

P. S. I put "force_init=1" in config

**Comment by rip1980** [comment]
Webmin 1.890 with Ubuntu 18.04.1 with "force_init=1" in config.

Unable to set firewall rules utilizing connection state (Established/Related) and think it's probably related to this ticket and #434 already so didn't want to open another.

**Comment by rold5** [comment]
Webmin 1.890 with debian 4.9.0-3-amd64

There is a "@known_args" array at around line 24 of firewall4-lib.pl and firewall6-lib.pl which is missing the newly supported '--ctstate' option. I added that option into those array initializers and this problem is resolved locally for me. rip1980 referenced #434 which does sound like the same problem I was seeing.

**Comment by jcameron** [comment]
@rold5 - good catch! I will include this fix in the next Webmin release.

**Comment by xingduan** [comment]
@jcameron should be "--ctstate" instead of "--cstate"

**Comment by jcameron** [comment]
Thanks, @xingduan  , will fix..

**Comment by nicorac** [comment]
Just updated to 1.900 but this bug is still there.
I've checked the firewall4-lib.pl file ant it contains the "--ctstate" flag.
I've already removed the 1.8xx firewall workaround (force_init).

This is the rule I can't see in firewall config (after a "Revert configuration", Webmin restart and reboot):
```
# iptables-save | grep RELATED
-A IS_BACK -m state --state RELATED,ESTABLISHED -j ACCEPT
```
It appears like this in firewall state list:
![webmin-fw-list](https://user-images.githubusercontent.com/2361673/48666780-8fb28400-eac8-11e8-9af0-8f9eb316036a.png)

If I edit the rule and save it, the list has duplicate conditions like this:
![webmin-fw-list-after-reedit](https://user-images.githubusercontent.com/2361673/48666792-ad7fe900-eac8-11e8-90ad-e9acdfdb3c0e.png)

When I finally save the "duplicate conditions" rule I got this error:
```
iptables-restore v1.6.1: unknown option "--state"
Error occurred at line: 153
Try `iptables-restore -h' or 'iptables-restore --help' for more information.
```

I suppose I need to remove/change the original --state options and keep only the new --ctstate ones, but it seems there's no way to do it.

**Comment by jcameron** [comment]
If you had an old rule that was created before the fix, it might still be incorrect. Try deleting that rule and re-creating it.

**Comment by nicorac** [comment]
Deleting and recreating it works, I'll fix them up on all of my machines with a bash script.

Anyway I suggest for some kind of "automatic fix" because there's a discrepancy between the _firewall rules_ list page (which recognizes both the old and new option) and the _rule edit_ page (which doesn't).
People who didn't follow this bug and update from 1.8xx to 1.900 could start wondering what's happening ;)

**Comment by jcameron** [comment]
I think an automatic fix for existing rules would be kind of dangerous. But I will make the list page consistent with the edit rule page.

**Comment by Fjor** [comment]
I resolved this error adding 'state' (without quotes) as an additional module in the rule definition. The final rule inserted by webmin is:
`iptables -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -m state --state RELATED,ESTABLISHED -j ACCEPT`
