### ISSUE TITLE
Squid is not supported by Webmin?

### ISSUE THREAD

**Issue by Ramaqele** [webmin/webmin#974]
just update squid about a week ago and i get the similar
Your version of Squid is not supported by Webmin. Only versions from 1.1 to 3.4 are supported by this module.
The command /usr/local/sbin/squid -v returned :

Squid Cache: Version 4.1
Service Name: squid
i am on webmin 1.890

**Comment by rostovtsev** [comment]
Hi, 

This has already been fixed in Git.

You can manually apply [the patch](https://github.com/webmin/webmin/blob/0ec818b517b4741ca28cbe6e06c54122260855f2/squid/index.cgi) but don't forget to replace:

```
#!/usr/local/bin/perl
```

to

```
#!/usr/bin/perl
```


You can also [install development](http://www.webmin.com/devel.html) version of Webmin that has this patched included as well.

**Comment by Ramaqele** [comment]
i am sorry i am not that knowledgeable in this thing i am just using webmin to administer my BSD boxes so by manually aplying the patch you mean i should copy and paste https://github.com/webmin/webmin/blob/0ec818b517b4741ca28cbe6e06c54122260855f2/squid/index.cgi into index.cgi and edit that first line

**Comment by rostovtsev** [comment]
Hi,

You would have to replace complete content of the file but keeping the first line unchanged.

**Comment by Ramaqele** [comment]
i did that with no luck and to more clear i am using FreeBsd 11.2 on my box and maybe it will work on the new update of webmin and on the index.cgi file that first line is commented out does it make any difference

**Comment by swelljoe** [comment]
The first line is not a comment, it is what's commonly called a "shebang". It means "run this script using the following interpreter". Ilia said to leave that line unchanged, because depending on your OS, Perl may be installed in a few different places. It needs to stay the same, because otherwise it won't find Perl and won't run. You would change everything *except* the first line (or you'd copy the whole file into place and change the first line to match all the rest of the CGI scripts in your Webmin installation).

**Comment by Ramaqele** [comment]
thank you very much @swelljoe  for the clarification you made it as easy as i dnt even know how to say it my webmin and can read squid configuration very well and @iliaross you guys are the best in terms of support and actually what finally made it work was copying and pasting the /squid/index.cgi you posted on the follwing thread [https://sourceforge.net/p/webadmin/bugs/4573/](url) keep up the good work.
