### ISSUE TITLE
Can't connect to Webmin port - “Cron 15430088014649 missing any time spec”

### ISSUE THREAD

**Issue by Bestulo** [webmin/webmin#994]
Webmin has started, but I can't access it from the web (can't curl/wget from terminal either). When I restart it, it throws the error I gave in the title. I've tracked the source of the error to this line of code:

https://github.com/webmin/webmin/blob/master/miniserv.pl#L5969

If I try to connect to any other port that is not Webmin's, the connection gets immediately rejected, but if I use Webmin's port, I wait and wait until it times out (in the browser, curl stays forever).

Does anybody have an idea of what I can do to fix this?

```
besto@host:~/tmp$ sudo /etc/init.d/webmin restart
Stopping Webmin server in /usr/share/webmin
Starting Webmin server in /usr/share/webmin
Cron 15430088014649 missing any time spec
besto@host:~/tmp$
```

**Comment by jcameron** [comment]
That error is just a warning, and wouldn't cause webmin to fail to start.

Make sure you are connecting using an http or https URL, depending on whether it's in SSL mode or not.

**Comment by Deaton64** [comment]
Hi,

I had the issue with the error message on a Centos 7 box, but could access Webmin fine.

This is the warning I had: `Cron 155004687829192 missing any time spec`
Which seems to refer to this file: `/etc/webmin/webmincron/crons/155004687829192.cron`

Contents of that file look like this:

```
func=scheduled_collect_system_info
id=155004687829192
module=system-status
boot=1
arg0=boot
```

However, when I check other Centos systems with Webmin running, the contents of the similar file look like this:

```
func=scheduled_collect_system_info
id=145216939427582
interval=300
module=system-status
```

So I matched my file to look like that:
```
func=scheduled_collect_system_info
id=155004687829192
interval=300
module=system-status
```

I no longer get the warning message with the Webmin service restart and all seems well.

I'm assuming that the interval means run every 300 seconds rather than run at boot. You may want to change it to once an hour (3600) or once a day (36400). I'm leaving mine at 300, as that's what my other systems are set at.

As @jcameron stated, this issue should not stop you accessing Webmin, it's all about Webmin Cron jobs.

Regards,

David
